const studentData = [
  { name: "Evelyn", project: "SCRUM", difficulty: 3, niceness: 4 },
  { name: "Evelyn", project: "W1D1-1", difficulty: 3, niceness: 3 },
  { name: "Evelyn", project: "W1D2-1", difficulty: 1, niceness: 3 },
  { name: "Evelyn", project: "W1D2-2", difficulty: 1, niceness: 4 },
  { name: "Evelyn", project: "W1D2-3", difficulty: 2, niceness: 3 },
  { name: "Evelyn", project: "W1D2-4", difficulty: 3, niceness: 4 },
  { name: "Evelyn", project: "W1D2-5", difficulty: 3, niceness: 4 },
  { name: "Evelyn", project: "W1D3-1", difficulty: 3, niceness: 4 },
  { name: "Evelyn", project: "W1D3-2", difficulty: 3, niceness: 4 },
  { name: "Evelyn", project: "W1D3-4", difficulty: 4, niceness: 4 },
  { name: "Evelyn", project: "W1D3-5", difficulty: 4, niceness: 4 },
  {
    name: "Evelyn",
    project: "W1D3 - Project - Guess-the-number",
    difficulty: 5,
    niceness: 5,
  },
  { name: "Evelyn", project: "W1D4-1", difficulty: 4, niceness: 5 },
  {
    name: "Evelyn",
    project: "W1D4 - Project - Kleurentoggle",
    difficulty: 3,
    niceness: 4,
  },
  {
    name: "Evelyn",
    project: "W1D5 - Project - Galgje",
    difficulty: 3,
    niceness: 3,
  },
  { name: "Evelyn", project: "W2D1-1", difficulty: 1, niceness: 5 },
  { name: "Evelyn", project: "W2D1-2", difficulty: 2, niceness: 5 },
  { name: "Evelyn", project: "W2D2-1", difficulty: 3, niceness: 4 },
  { name: "Evelyn", project: "W2D2-2", difficulty: 3, niceness: 4 },
  { name: "Evelyn", project: "W2D2-3", difficulty: 3, niceness: 4 },
  { name: "Evelyn", project: "W2D3-1", difficulty: 4, niceness: 4 },
  { name: "Evelyn", project: "W2D3-2", difficulty: 1, niceness: 3 },
  { name: "Evelyn", project: "W2D3-3", difficulty: 4, niceness: 4 },
  { name: "Evelyn", project: "W2D4-1", difficulty: 1, niceness: 3 },
  { name: "Evelyn", project: "W2D4-2", difficulty: 4, niceness: 4 },
  { name: "Evelyn", project: "W2D4-3", difficulty: 1, niceness: 3 },
  {
    name: "Evelyn",
    project: "W2D5 - Project - Filmzoeker",
    difficulty: 3,
    niceness: 4,
  },
  { name: "Evelyn", project: "W3D1-1", difficulty: 3, niceness: 4 },
  { name: "Evelyn", project: "W3D1-2", difficulty: 2, niceness: 4 },
  { name: "Evelyn", project: "W3D1-3", difficulty: 3, niceness: 4 },
  { name: "Evelyn", project: "W3D1-4", difficulty: 3, niceness: 3 },
  { name: "Evelyn", project: "W3D2-1", difficulty: 2, niceness: 4 },
  { name: "Evelyn", project: "W3D2-2", difficulty: 3, niceness: 3 },
  { name: "Evelyn", project: "W3D2-3", difficulty: 3, niceness: 5 },
  { name: "Evelyn", project: "W3D3-1", difficulty: 4, niceness: 4 },
  { name: "Evelyn", project: "W3D3-2", difficulty: 4, niceness: 5 },
  { name: "Evelyn", project: "W3D3-3", difficulty: 3, niceness: 5 },
  { name: "Evelyn", project: "W3D3-4", difficulty: 4, niceness: 5 },
  { name: "Evelyn", project: "W3D4-1", difficulty: 5, niceness: 5 },
  { name: "Evelyn", project: "W3D4-2", difficulty: 1, niceness: 5 },
  {
    name: "Evelyn",
    project: "W3D5 - Project - Todo-List",
    difficulty: 2,
    niceness: 5,
  },
  { name: "Evelyn", project: "W4D2-1", difficulty: 1, niceness: 5 },
  { name: "Evelyn", project: "W4D2-2", difficulty: 1, niceness: 5 },
  { name: "Evelyn", project: "W4D2-3", difficulty: 1, niceness: 5 },
  { name: "Evelyn", project: "W4D2-4", difficulty: 1, niceness: 5 },
  { name: "Evelyn", project: "W4D3-1", difficulty: 1, niceness: 5 },
  { name: "Evelyn", project: "W4D3-2", difficulty: 1, niceness: 5 },
  { name: "Evelyn", project: "W4D3-3", difficulty: 1, niceness: 5 },
  { name: "Evelyn", project: "W4D3-4", difficulty: 1, niceness: 5 },
  { name: "Evelyn", project: "W4D3-5", difficulty: 1, niceness: 5 },
  {
    name: "Evelyn",
    project: "W4D3 - Project - Next-Level CSS",
    difficulty: 1,
    niceness: 5,
  },
  { name: "Evelyn", project: "W5D4-1", difficulty: 3, niceness: 4 },
  {
    name: "Evelyn",
    project: "W5D5 - Project - Lil_Playlist",
    difficulty: 4,
    niceness: 3,
  },
  { name: "Evelyn", project: "W6D1-1", difficulty: 5, niceness: 5 },
  { name: "Evelyn", project: "W6D2-1", difficulty: 4, niceness: 3 },
  {
    name: "Evelyn",
    project: "W6D2 - Project - Eindopdracht",
    difficulty: 5,
    niceness: 5,
  },
  { name: "Aranka", project: "SCRUM", difficulty: 1, niceness: 1 },
  { name: "Aranka", project: "W1D1-1", difficulty: 4, niceness: 3 },
  { name: "Aranka", project: "W1D2-1", difficulty: 3, niceness: 1 },
  { name: "Aranka", project: "W1D2-2", difficulty: 3, niceness: 2 },
  { name: "Aranka", project: "W1D2-3", difficulty: 4, niceness: 1 },
  { name: "Aranka", project: "W1D2-4", difficulty: 2, niceness: 3 },
  { name: "Aranka", project: "W1D2-5", difficulty: 4, niceness: 2 },
  { name: "Aranka", project: "W1D3-1", difficulty: 3, niceness: 2 },
  { name: "Aranka", project: "W1D3-2", difficulty: 2, niceness: 1 },
  { name: "Aranka", project: "W1D3-4", difficulty: 1, niceness: 2 },
  { name: "Aranka", project: "W1D3-5", difficulty: 4, niceness: 1 },
  {
    name: "Aranka",
    project: "W1D3 - Project - Guess-the-number",
    difficulty: 2,
    niceness: 3,
  },
  { name: "Aranka", project: "W1D4-1", difficulty: 3, niceness: 2 },
  {
    name: "Aranka",
    project: "W1D4 - Project - Kleurentoggle",
    difficulty: 4,
    niceness: 3,
  },
  {
    name: "Aranka",
    project: "W1D5 - Project - Galgje",
    difficulty: 4,
    niceness: 1,
  },
  { name: "Aranka", project: "W2D1-1", difficulty: 2, niceness: 4 },
  { name: "Aranka", project: "W2D1-2", difficulty: 4, niceness: 4 },
  { name: "Aranka", project: "W2D2-1", difficulty: 3, niceness: 4 },
  { name: "Aranka", project: "W2D2-2", difficulty: 3, niceness: 4 },
  { name: "Aranka", project: "W2D2-3", difficulty: 1, niceness: 4 },
  { name: "Aranka", project: "W2D3-1", difficulty: 4, niceness: 3 },
  { name: "Aranka", project: "W2D3-2", difficulty: 4, niceness: 1 },
  { name: "Aranka", project: "W2D3-3", difficulty: 1, niceness: 1 },
  { name: "Aranka", project: "W2D4-1", difficulty: 1, niceness: 4 },
  { name: "Aranka", project: "W2D4-2", difficulty: 2, niceness: 3 },
  { name: "Aranka", project: "W2D4-3", difficulty: 2, niceness: 3 },
  {
    name: "Aranka",
    project: "W2D5 - Project - Filmzoeker",
    difficulty: 2,
    niceness: 2,
  },
  { name: "Aranka", project: "W3D1-1", difficulty: 4, niceness: 2 },
  { name: "Aranka", project: "W3D1-2", difficulty: 3, niceness: 2 },
  { name: "Aranka", project: "W3D1-3", difficulty: 1, niceness: 4 },
  { name: "Aranka", project: "W3D1-4", difficulty: 1, niceness: 3 },
  { name: "Aranka", project: "W3D2-1", difficulty: 1, niceness: 3 },
  { name: "Aranka", project: "W3D2-2", difficulty: 2, niceness: 3 },
  { name: "Aranka", project: "W3D2-3", difficulty: 2, niceness: 3 },
  { name: "Aranka", project: "W3D3-1", difficulty: 2, niceness: 2 },
  { name: "Aranka", project: "W3D3-2", difficulty: 4, niceness: 3 },
  { name: "Aranka", project: "W3D3-3", difficulty: 3, niceness: 3 },
  { name: "Aranka", project: "W3D3-4", difficulty: 1, niceness: 3 },
  { name: "Aranka", project: "W3D4-1", difficulty: 1, niceness: 1 },
  { name: "Aranka", project: "W3D4-2", difficulty: 3, niceness: 2 },
  {
    name: "Aranka",
    project: "W3D5 - Project - Todo-List",
    difficulty: 1,
    niceness: 1,
  },
  { name: "Aranka", project: "W4D2-1", difficulty: 2, niceness: 1 },
  { name: "Aranka", project: "W4D2-2", difficulty: 3, niceness: 2 },
  { name: "Aranka", project: "W4D2-3", difficulty: 2, niceness: 2 },
  { name: "Aranka", project: "W4D2-4", difficulty: 3, niceness: 4 },
  { name: "Aranka", project: "W4D3-1", difficulty: 2, niceness: 1 },
  { name: "Aranka", project: "W4D3-2", difficulty: 4, niceness: 4 },
  { name: "Aranka", project: "W4D3-3", difficulty: 3, niceness: 1 },
  { name: "Aranka", project: "W4D3-4", difficulty: 3, niceness: 1 },
  { name: "Aranka", project: "W4D3-5", difficulty: 4, niceness: 3 },
  {
    name: "Aranka",
    project: "W4D3 - Project - Next-Level CSS",
    difficulty: 4,
    niceness: 4,
  },
  { name: "Aranka", project: "W5D4-1", difficulty: 1, niceness: 3 },
  {
    name: "Aranka",
    project: "W5D5 - Project - Lil_Playlist",
    difficulty: 3,
    niceness: 2,
  },
  { name: "Aranka", project: "W6D1-1", difficulty: 1, niceness: 1 },
  { name: "Aranka", project: "W6D2-1", difficulty: 2, niceness: 2 },
  {
    name: "Aranka",
    project: "W6D2 - Project - Eindopdracht",
    difficulty: 3,
    niceness: 4,
  },
  { name: "Floris", project: "SCRUM", difficulty: 2, niceness: 1 },
  { name: "Floris", project: "W1D1-1", difficulty: 4, niceness: 3 },
  { name: "Floris", project: "W1D2-1", difficulty: 1, niceness: 2 },
  { name: "Floris", project: "W1D2-2", difficulty: 1, niceness: 4 },
  { name: "Floris", project: "W1D2-3", difficulty: 1, niceness: 4 },
  { name: "Floris", project: "W1D2-4", difficulty: 3, niceness: 4 },
  { name: "Floris", project: "W1D2-5", difficulty: 1, niceness: 3 },
  { name: "Floris", project: "W1D3-1", difficulty: 2, niceness: 4 },
  { name: "Floris", project: "W1D3-2", difficulty: 4, niceness: 4 },
  { name: "Floris", project: "W1D3-4", difficulty: 4, niceness: 2 },
  { name: "Floris", project: "W1D3-5", difficulty: 2, niceness: 4 },
  {
    name: "Floris",
    project: "W1D3 - Project - Guess-the-number",
    difficulty: 2,
    niceness: 2,
  },
  { name: "Floris", project: "W1D4-1", difficulty: 1, niceness: 3 },
  {
    name: "Floris",
    project: "W1D4 - Project - Kleurentoggle",
    difficulty: 4,
    niceness: 3,
  },
  {
    name: "Floris",
    project: "W1D5 - Project - Galgje",
    difficulty: 4,
    niceness: 4,
  },
  { name: "Floris", project: "W2D1-1", difficulty: 2, niceness: 2 },
  { name: "Floris", project: "W2D1-2", difficulty: 4, niceness: 1 },
  { name: "Floris", project: "W2D2-1", difficulty: 4, niceness: 1 },
  { name: "Floris", project: "W2D2-2", difficulty: 2, niceness: 2 },
  { name: "Floris", project: "W2D2-3", difficulty: 4, niceness: 2 },
  { name: "Floris", project: "W2D3-1", difficulty: 1, niceness: 1 },
  { name: "Floris", project: "W2D3-2", difficulty: 1, niceness: 2 },
  { name: "Floris", project: "W2D3-3", difficulty: 3, niceness: 3 },
  { name: "Floris", project: "W2D4-1", difficulty: 4, niceness: 4 },
  { name: "Floris", project: "W2D4-2", difficulty: 3, niceness: 1 },
  { name: "Floris", project: "W2D4-3", difficulty: 4, niceness: 1 },
  {
    name: "Floris",
    project: "W2D5 - Project - Filmzoeker",
    difficulty: 4,
    niceness: 1,
  },
  { name: "Floris", project: "W3D1-1", difficulty: 4, niceness: 3 },
  { name: "Floris", project: "W3D1-2", difficulty: 2, niceness: 3 },
  { name: "Floris", project: "W3D1-3", difficulty: 2, niceness: 3 },
  { name: "Floris", project: "W3D1-4", difficulty: 3, niceness: 3 },
  { name: "Floris", project: "W3D2-1", difficulty: 3, niceness: 2 },
  { name: "Floris", project: "W3D2-2", difficulty: 2, niceness: 2 },
  { name: "Floris", project: "W3D2-3", difficulty: 3, niceness: 2 },
  { name: "Floris", project: "W3D3-1", difficulty: 4, niceness: 4 },
  { name: "Floris", project: "W3D3-2", difficulty: 2, niceness: 4 },
  { name: "Floris", project: "W3D3-3", difficulty: 2, niceness: 1 },
  { name: "Floris", project: "W3D3-4", difficulty: 3, niceness: 2 },
  { name: "Floris", project: "W3D4-1", difficulty: 1, niceness: 3 },
  { name: "Floris", project: "W3D4-2", difficulty: 2, niceness: 2 },
  {
    name: "Floris",
    project: "W3D5 - Project - Todo-List",
    difficulty: 4,
    niceness: 2,
  },
  { name: "Floris", project: "W4D2-1", difficulty: 1, niceness: 4 },
  { name: "Floris", project: "W4D2-2", difficulty: 2, niceness: 3 },
  { name: "Floris", project: "W4D2-3", difficulty: 2, niceness: 4 },
  { name: "Floris", project: "W4D2-4", difficulty: 1, niceness: 2 },
  { name: "Floris", project: "W4D3-1", difficulty: 1, niceness: 4 },
  { name: "Floris", project: "W4D3-2", difficulty: 4, niceness: 4 },
  { name: "Floris", project: "W4D3-3", difficulty: 3, niceness: 2 },
  { name: "Floris", project: "W4D3-4", difficulty: 2, niceness: 2 },
  { name: "Floris", project: "W4D3-5", difficulty: 4, niceness: 1 },
  {
    name: "Floris",
    project: "W4D3 - Project - Next-Level CSS",
    difficulty: 2,
    niceness: 2,
  },
  { name: "Floris", project: "W5D4-1", difficulty: 1, niceness: 3 },
  {
    name: "Floris",
    project: "W5D5 - Project - Lil_Playlist",
    difficulty: 3,
    niceness: 1,
  },
  { name: "Floris", project: "W6D1-1", difficulty: 3, niceness: 2 },
  { name: "Floris", project: "W6D2-1", difficulty: 1, niceness: 1 },
  {
    name: "Floris",
    project: "W6D2 - Project - Eindopdracht",
    difficulty: 4,
    niceness: 1,
  },
  { name: "Hector", project: "SCRUM", difficulty: 1, niceness: 2 },
  { name: "Hector", project: "W1D1-1", difficulty: 1, niceness: 4 },
  { name: "Hector", project: "W1D2-1", difficulty: 2, niceness: 4 },
  { name: "Hector", project: "W1D2-2", difficulty: 2, niceness: 3 },
  { name: "Hector", project: "W1D2-3", difficulty: 1, niceness: 2 },
  { name: "Hector", project: "W1D2-4", difficulty: 1, niceness: 3 },
  { name: "Hector", project: "W1D2-5", difficulty: 3, niceness: 1 },
  { name: "Hector", project: "W1D3-1", difficulty: 1, niceness: 4 },
  { name: "Hector", project: "W1D3-2", difficulty: 4, niceness: 3 },
  { name: "Hector", project: "W1D3-4", difficulty: 3, niceness: 1 },
  { name: "Hector", project: "W1D3-5", difficulty: 4, niceness: 2 },
  {
    name: "Hector",
    project: "W1D3 - Project - Guess-the-number",
    difficulty: 3,
    niceness: 1,
  },
  { name: "Hector", project: "W1D4-1", difficulty: 1, niceness: 1 },
  {
    name: "Hector",
    project: "W1D4 - Project - Kleurentoggle",
    difficulty: 1,
    niceness: 3,
  },
  {
    name: "Hector",
    project: "W1D5 - Project - Galgje",
    difficulty: 2,
    niceness: 4,
  },
  { name: "Hector", project: "W2D1-1", difficulty: 4, niceness: 4 },
  { name: "Hector", project: "W2D1-2", difficulty: 3, niceness: 2 },
  { name: "Hector", project: "W2D2-1", difficulty: 4, niceness: 3 },
  { name: "Hector", project: "W2D2-2", difficulty: 1, niceness: 2 },
  { name: "Hector", project: "W2D2-3", difficulty: 3, niceness: 2 },
  { name: "Hector", project: "W2D3-1", difficulty: 3, niceness: 1 },
  { name: "Hector", project: "W2D3-2", difficulty: 4, niceness: 2 },
  { name: "Hector", project: "W2D3-3", difficulty: 4, niceness: 2 },
  { name: "Hector", project: "W2D4-1", difficulty: 2, niceness: 4 },
  { name: "Hector", project: "W2D4-2", difficulty: 4, niceness: 1 },
  { name: "Hector", project: "W2D4-3", difficulty: 3, niceness: 2 },
  {
    name: "Hector",
    project: "W2D5 - Project - Filmzoeker",
    difficulty: 4,
    niceness: 1,
  },
  { name: "Hector", project: "W3D1-1", difficulty: 1, niceness: 1 },
  { name: "Hector", project: "W3D1-2", difficulty: 1, niceness: 4 },
  { name: "Hector", project: "W3D1-3", difficulty: 3, niceness: 2 },
  { name: "Hector", project: "W3D1-4", difficulty: 4, niceness: 3 },
  { name: "Hector", project: "W3D2-1", difficulty: 1, niceness: 3 },
  { name: "Hector", project: "W3D2-2", difficulty: 4, niceness: 3 },
  { name: "Hector", project: "W3D2-3", difficulty: 2, niceness: 1 },
  { name: "Hector", project: "W3D3-1", difficulty: 4, niceness: 4 },
  { name: "Hector", project: "W3D3-2", difficulty: 3, niceness: 1 },
  { name: "Hector", project: "W3D3-3", difficulty: 2, niceness: 4 },
  { name: "Hector", project: "W3D3-4", difficulty: 4, niceness: 1 },
  { name: "Hector", project: "W3D4-1", difficulty: 3, niceness: 4 },
  { name: "Hector", project: "W3D4-2", difficulty: 1, niceness: 4 },
  {
    name: "Hector",
    project: "W3D5 - Project - Todo-List",
    difficulty: 2,
    niceness: 4,
  },
  { name: "Hector", project: "W4D2-1", difficulty: 1, niceness: 1 },
  { name: "Hector", project: "W4D2-2", difficulty: 2, niceness: 1 },
  { name: "Hector", project: "W4D2-3", difficulty: 3, niceness: 3 },
  { name: "Hector", project: "W4D2-4", difficulty: 1, niceness: 3 },
  { name: "Hector", project: "W4D3-1", difficulty: 3, niceness: 3 },
  { name: "Hector", project: "W4D3-2", difficulty: 1, niceness: 4 },
  { name: "Hector", project: "W4D3-3", difficulty: 3, niceness: 1 },
  { name: "Hector", project: "W4D3-4", difficulty: 1, niceness: 3 },
  { name: "Hector", project: "W4D3-5", difficulty: 1, niceness: 2 },
  {
    name: "Hector",
    project: "W4D3 - Project - Next-Level CSS",
    difficulty: 3,
    niceness: 1,
  },
  { name: "Hector", project: "W5D4-1", difficulty: 3, niceness: 4 },
  {
    name: "Hector",
    project: "W5D5 - Project - Lil_Playlist",
    difficulty: 3,
    niceness: 1,
  },
  { name: "Hector", project: "W6D1-1", difficulty: 1, niceness: 1 },
  { name: "Hector", project: "W6D2-1", difficulty: 4, niceness: 2 },
  {
    name: "Hector",
    project: "W6D2 - Project - Eindopdracht",
    difficulty: 2,
    niceness: 4,
  },
  { name: "Martina", project: "SCRUM", difficulty: 1, niceness: 1 },
  { name: "Martina", project: "W1D1-1", difficulty: 4, niceness: 1 },
  { name: "Martina", project: "W1D2-1", difficulty: 3, niceness: 3 },
  { name: "Martina", project: "W1D2-2", difficulty: 2, niceness: 1 },
  { name: "Martina", project: "W1D2-3", difficulty: 2, niceness: 1 },
  { name: "Martina", project: "W1D2-4", difficulty: 4, niceness: 2 },
  { name: "Martina", project: "W1D2-5", difficulty: 3, niceness: 4 },
  { name: "Martina", project: "W1D3-1", difficulty: 3, niceness: 4 },
  { name: "Martina", project: "W1D3-2", difficulty: 2, niceness: 1 },
  { name: "Martina", project: "W1D3-4", difficulty: 3, niceness: 2 },
  { name: "Martina", project: "W1D3-5", difficulty: 1, niceness: 1 },
  {
    name: "Martina",
    project: "W1D3 - Project - Guess-the-number",
    difficulty: 2,
    niceness: 2,
  },
  { name: "Martina", project: "W1D4-1", difficulty: 4, niceness: 2 },
  {
    name: "Martina",
    project: "W1D4 - Project - Kleurentoggle",
    difficulty: 1,
    niceness: 3,
  },
  {
    name: "Martina",
    project: "W1D5 - Project - Galgje",
    difficulty: 1,
    niceness: 4,
  },
  { name: "Martina", project: "W2D1-1", difficulty: 1, niceness: 4 },
  { name: "Martina", project: "W2D1-2", difficulty: 4, niceness: 2 },
  { name: "Martina", project: "W2D2-1", difficulty: 4, niceness: 1 },
  { name: "Martina", project: "W2D2-2", difficulty: 3, niceness: 3 },
  { name: "Martina", project: "W2D2-3", difficulty: 3, niceness: 1 },
  { name: "Martina", project: "W2D3-1", difficulty: 4, niceness: 2 },
  { name: "Martina", project: "W2D3-2", difficulty: 3, niceness: 4 },
  { name: "Martina", project: "W2D3-3", difficulty: 3, niceness: 3 },
  { name: "Martina", project: "W2D4-1", difficulty: 1, niceness: 4 },
  { name: "Martina", project: "W2D4-2", difficulty: 3, niceness: 4 },
  { name: "Martina", project: "W2D4-3", difficulty: 3, niceness: 4 },
  {
    name: "Martina",
    project: "W2D5 - Project - Filmzoeker",
    difficulty: 2,
    niceness: 4,
  },
  { name: "Martina", project: "W3D1-1", difficulty: 1, niceness: 1 },
  { name: "Martina", project: "W3D1-2", difficulty: 3, niceness: 3 },
  { name: "Martina", project: "W3D1-3", difficulty: 3, niceness: 1 },
  { name: "Martina", project: "W3D1-4", difficulty: 3, niceness: 2 },
  { name: "Martina", project: "W3D2-1", difficulty: 1, niceness: 2 },
  { name: "Martina", project: "W3D2-2", difficulty: 2, niceness: 4 },
  { name: "Martina", project: "W3D2-3", difficulty: 3, niceness: 1 },
  { name: "Martina", project: "W3D3-1", difficulty: 1, niceness: 4 },
  { name: "Martina", project: "W3D3-2", difficulty: 4, niceness: 1 },
  { name: "Martina", project: "W3D3-3", difficulty: 3, niceness: 3 },
  { name: "Martina", project: "W3D3-4", difficulty: 2, niceness: 3 },
  { name: "Martina", project: "W3D4-1", difficulty: 4, niceness: 4 },
  { name: "Martina", project: "W3D4-2", difficulty: 3, niceness: 1 },
  {
    name: "Martina",
    project: "W3D5 - Project - Todo-List",
    difficulty: 2,
    niceness: 3,
  },
  { name: "Martina", project: "W4D2-1", difficulty: 3, niceness: 4 },
  { name: "Martina", project: "W4D2-2", difficulty: 1, niceness: 2 },
  { name: "Martina", project: "W4D2-3", difficulty: 3, niceness: 4 },
  { name: "Martina", project: "W4D2-4", difficulty: 4, niceness: 1 },
  { name: "Martina", project: "W4D3-1", difficulty: 2, niceness: 4 },
  { name: "Martina", project: "W4D3-2", difficulty: 1, niceness: 3 },
  { name: "Martina", project: "W4D3-3", difficulty: 2, niceness: 4 },
  { name: "Martina", project: "W4D3-4", difficulty: 4, niceness: 1 },
  { name: "Martina", project: "W4D3-5", difficulty: 3, niceness: 2 },
  {
    name: "Martina",
    project: "W4D3 - Project - Next-Level CSS",
    difficulty: 3,
    niceness: 4,
  },
  { name: "Martina", project: "W5D4-1", difficulty: 1, niceness: 4 },
  {
    name: "Martina",
    project: "W5D5 - Project - Lil_Playlist",
    difficulty: 1,
    niceness: 1,
  },
  { name: "Martina", project: "W6D1-1", difficulty: 2, niceness: 1 },
  { name: "Martina", project: "W6D2-1", difficulty: 1, niceness: 4 },
  {
    name: "Martina",
    project: "W6D2 - Project - Eindopdracht",
    difficulty: 1,
    niceness: 4,
  },
  { name: "Maurits", project: "SCRUM", difficulty: 3, niceness: 4 },
  { name: "Maurits", project: "W1D1-1", difficulty: 4, niceness: 3 },
  { name: "Maurits", project: "W1D2-1", difficulty: 2, niceness: 2 },
  { name: "Maurits", project: "W1D2-2", difficulty: 1, niceness: 4 },
  { name: "Maurits", project: "W1D2-3", difficulty: 2, niceness: 2 },
  { name: "Maurits", project: "W1D2-4", difficulty: 3, niceness: 1 },
  { name: "Maurits", project: "W1D2-5", difficulty: 2, niceness: 3 },
  { name: "Maurits", project: "W1D3-1", difficulty: 2, niceness: 4 },
  { name: "Maurits", project: "W1D3-2", difficulty: 2, niceness: 2 },
  { name: "Maurits", project: "W1D3-4", difficulty: 2, niceness: 2 },
  { name: "Maurits", project: "W1D3-5", difficulty: 1, niceness: 3 },
  {
    name: "Maurits",
    project: "W1D3 - Project - Guess-the-number",
    difficulty: 1,
    niceness: 1,
  },
  { name: "Maurits", project: "W1D4-1", difficulty: 3, niceness: 4 },
  {
    name: "Maurits",
    project: "W1D4 - Project - Kleurentoggle",
    difficulty: 4,
    niceness: 1,
  },
  {
    name: "Maurits",
    project: "W1D5 - Project - Galgje",
    difficulty: 3,
    niceness: 2,
  },
  { name: "Maurits", project: "W2D1-1", difficulty: 1, niceness: 1 },
  { name: "Maurits", project: "W2D1-2", difficulty: 2, niceness: 3 },
  { name: "Maurits", project: "W2D2-1", difficulty: 1, niceness: 2 },
  { name: "Maurits", project: "W2D2-2", difficulty: 4, niceness: 1 },
  { name: "Maurits", project: "W2D2-3", difficulty: 2, niceness: 2 },
  { name: "Maurits", project: "W2D3-1", difficulty: 2, niceness: 2 },
  { name: "Maurits", project: "W2D3-2", difficulty: 3, niceness: 3 },
  { name: "Maurits", project: "W2D3-3", difficulty: 2, niceness: 1 },
  { name: "Maurits", project: "W2D4-1", difficulty: 1, niceness: 3 },
  { name: "Maurits", project: "W2D4-2", difficulty: 3, niceness: 2 },
  { name: "Maurits", project: "W2D4-3", difficulty: 3, niceness: 3 },
  {
    name: "Maurits",
    project: "W2D5 - Project - Filmzoeker",
    difficulty: 3,
    niceness: 1,
  },
  { name: "Maurits", project: "W3D1-1", difficulty: 4, niceness: 4 },
  { name: "Maurits", project: "W3D1-2", difficulty: 1, niceness: 3 },
  { name: "Maurits", project: "W3D1-3", difficulty: 1, niceness: 4 },
  { name: "Maurits", project: "W3D1-4", difficulty: 1, niceness: 2 },
  { name: "Maurits", project: "W3D2-1", difficulty: 1, niceness: 4 },
  { name: "Maurits", project: "W3D2-2", difficulty: 1, niceness: 1 },
  { name: "Maurits", project: "W3D2-3", difficulty: 4, niceness: 3 },
  { name: "Maurits", project: "W3D3-1", difficulty: 1, niceness: 1 },
  { name: "Maurits", project: "W3D3-2", difficulty: 2, niceness: 1 },
  { name: "Maurits", project: "W3D3-3", difficulty: 1, niceness: 3 },
  { name: "Maurits", project: "W3D3-4", difficulty: 4, niceness: 1 },
  { name: "Maurits", project: "W3D4-1", difficulty: 4, niceness: 4 },
  { name: "Maurits", project: "W3D4-2", difficulty: 1, niceness: 3 },
  {
    name: "Maurits",
    project: "W3D5 - Project - Todo-List",
    difficulty: 3,
    niceness: 4,
  },
  { name: "Maurits", project: "W4D2-1", difficulty: 3, niceness: 1 },
  { name: "Maurits", project: "W4D2-2", difficulty: 4, niceness: 4 },
  { name: "Maurits", project: "W4D2-3", difficulty: 4, niceness: 1 },
  { name: "Maurits", project: "W4D2-4", difficulty: 2, niceness: 3 },
  { name: "Maurits", project: "W4D3-1", difficulty: 3, niceness: 1 },
  { name: "Maurits", project: "W4D3-2", difficulty: 3, niceness: 2 },
  { name: "Maurits", project: "W4D3-3", difficulty: 3, niceness: 4 },
  { name: "Maurits", project: "W4D3-4", difficulty: 1, niceness: 3 },
  { name: "Maurits", project: "W4D3-5", difficulty: 2, niceness: 1 },
  {
    name: "Maurits",
    project: "W4D3 - Project - Next-Level CSS",
    difficulty: 2,
    niceness: 3,
  },
  { name: "Maurits", project: "W5D4-1", difficulty: 1, niceness: 3 },
  {
    name: "Maurits",
    project: "W5D5 - Project - Lil_Playlist",
    difficulty: 4,
    niceness: 2,
  },
  { name: "Maurits", project: "W6D1-1", difficulty: 1, niceness: 3 },
  { name: "Maurits", project: "W6D2-1", difficulty: 1, niceness: 4 },
  {
    name: "Maurits",
    project: "W6D2 - Project - Eindopdracht",
    difficulty: 3,
    niceness: 3,
  },
  { name: "Rahima", project: "SCRUM", difficulty: 2, niceness: 4 },
  { name: "Rahima", project: "W1D1-1", difficulty: 3, niceness: 4 },
  { name: "Rahima", project: "W1D2-1", difficulty: 2, niceness: 4 },
  { name: "Rahima", project: "W1D2-2", difficulty: 1, niceness: 2 },
  { name: "Rahima", project: "W1D2-3", difficulty: 1, niceness: 3 },
  { name: "Rahima", project: "W1D2-4", difficulty: 1, niceness: 2 },
  { name: "Rahima", project: "W1D2-5", difficulty: 1, niceness: 3 },
  { name: "Rahima", project: "W1D3-1", difficulty: 1, niceness: 1 },
  { name: "Rahima", project: "W1D3-2", difficulty: 2, niceness: 4 },
  { name: "Rahima", project: "W1D3-4", difficulty: 1, niceness: 2 },
  { name: "Rahima", project: "W1D3-5", difficulty: 2, niceness: 2 },
  {
    name: "Rahima",
    project: "W1D3 - Project - Guess-the-number",
    difficulty: 3,
    niceness: 1,
  },
  { name: "Rahima", project: "W1D4-1", difficulty: 4, niceness: 3 },
  {
    name: "Rahima",
    project: "W1D4 - Project - Kleurentoggle",
    difficulty: 2,
    niceness: 4,
  },
  {
    name: "Rahima",
    project: "W1D5 - Project - Galgje",
    difficulty: 3,
    niceness: 3,
  },
  { name: "Rahima", project: "W2D1-1", difficulty: 2, niceness: 2 },
  { name: "Rahima", project: "W2D1-2", difficulty: 3, niceness: 1 },
  { name: "Rahima", project: "W2D2-1", difficulty: 1, niceness: 1 },
  { name: "Rahima", project: "W2D2-2", difficulty: 1, niceness: 1 },
  { name: "Rahima", project: "W2D2-3", difficulty: 4, niceness: 2 },
  { name: "Rahima", project: "W2D3-1", difficulty: 1, niceness: 1 },
  { name: "Rahima", project: "W2D3-2", difficulty: 1, niceness: 4 },
  { name: "Rahima", project: "W2D3-3", difficulty: 4, niceness: 2 },
  { name: "Rahima", project: "W2D4-1", difficulty: 4, niceness: 4 },
  { name: "Rahima", project: "W2D4-2", difficulty: 4, niceness: 4 },
  { name: "Rahima", project: "W2D4-3", difficulty: 2, niceness: 3 },
  {
    name: "Rahima",
    project: "W2D5 - Project - Filmzoeker",
    difficulty: 3,
    niceness: 1,
  },
  { name: "Rahima", project: "W3D1-1", difficulty: 1, niceness: 1 },
  { name: "Rahima", project: "W3D1-2", difficulty: 1, niceness: 2 },
  { name: "Rahima", project: "W3D1-3", difficulty: 2, niceness: 3 },
  { name: "Rahima", project: "W3D1-4", difficulty: 2, niceness: 4 },
  { name: "Rahima", project: "W3D2-1", difficulty: 3, niceness: 2 },
  { name: "Rahima", project: "W3D2-2", difficulty: 1, niceness: 4 },
  { name: "Rahima", project: "W3D2-3", difficulty: 2, niceness: 1 },
  { name: "Rahima", project: "W3D3-1", difficulty: 3, niceness: 1 },
  { name: "Rahima", project: "W3D3-2", difficulty: 4, niceness: 4 },
  { name: "Rahima", project: "W3D3-3", difficulty: 1, niceness: 4 },
  { name: "Rahima", project: "W3D3-4", difficulty: 2, niceness: 2 },
  { name: "Rahima", project: "W3D4-1", difficulty: 1, niceness: 2 },
  { name: "Rahima", project: "W3D4-2", difficulty: 3, niceness: 3 },
  {
    name: "Rahima",
    project: "W3D5 - Project - Todo-List",
    difficulty: 2,
    niceness: 4,
  },
  { name: "Rahima", project: "W4D2-1", difficulty: 2, niceness: 4 },
  { name: "Rahima", project: "W4D2-2", difficulty: 4, niceness: 3 },
  { name: "Rahima", project: "W4D2-3", difficulty: 3, niceness: 3 },
  { name: "Rahima", project: "W4D2-4", difficulty: 4, niceness: 1 },
  { name: "Rahima", project: "W4D3-1", difficulty: 2, niceness: 1 },
  { name: "Rahima", project: "W4D3-2", difficulty: 1, niceness: 1 },
  { name: "Rahima", project: "W4D3-3", difficulty: 2, niceness: 1 },
  { name: "Rahima", project: "W4D3-4", difficulty: 2, niceness: 2 },
  { name: "Rahima", project: "W4D3-5", difficulty: 3, niceness: 2 },
  {
    name: "Rahima",
    project: "W4D3 - Project - Next-Level CSS",
    difficulty: 1,
    niceness: 2,
  },
  { name: "Rahima", project: "W5D4-1", difficulty: 3, niceness: 3 },
  {
    name: "Rahima",
    project: "W5D5 - Project - Lil_Playlist",
    difficulty: 2,
    niceness: 3,
  },
  { name: "Rahima", project: "W6D1-1", difficulty: 4, niceness: 4 },
  { name: "Rahima", project: "W6D2-1", difficulty: 1, niceness: 4 },
  {
    name: "Rahima",
    project: "W6D2 - Project - Eindopdracht",
    difficulty: 4,
    niceness: 1,
  },
  { name: "Sandra", project: "SCRUM", difficulty: 4, niceness: 1 },
  { name: "Sandra", project: "W1D1-1", difficulty: 2, niceness: 4 },
  { name: "Sandra", project: "W1D2-1", difficulty: 3, niceness: 4 },
  { name: "Sandra", project: "W1D2-2", difficulty: 3, niceness: 2 },
  { name: "Sandra", project: "W1D2-3", difficulty: 3, niceness: 4 },
  { name: "Sandra", project: "W1D2-4", difficulty: 3, niceness: 1 },
  { name: "Sandra", project: "W1D2-5", difficulty: 4, niceness: 3 },
  { name: "Sandra", project: "W1D3-1", difficulty: 1, niceness: 1 },
  { name: "Sandra", project: "W1D3-2", difficulty: 1, niceness: 1 },
  { name: "Sandra", project: "W1D3-4", difficulty: 3, niceness: 3 },
  { name: "Sandra", project: "W1D3-5", difficulty: 4, niceness: 3 },
  {
    name: "Sandra",
    project: "W1D3 - Project - Guess-the-number",
    difficulty: 2,
    niceness: 4,
  },
  { name: "Sandra", project: "W1D4-1", difficulty: 3, niceness: 2 },
  {
    name: "Sandra",
    project: "W1D4 - Project - Kleurentoggle",
    difficulty: 1,
    niceness: 3,
  },
  {
    name: "Sandra",
    project: "W1D5 - Project - Galgje",
    difficulty: 3,
    niceness: 3,
  },
  { name: "Sandra", project: "W2D1-1", difficulty: 4, niceness: 1 },
  { name: "Sandra", project: "W2D1-2", difficulty: 4, niceness: 3 },
  { name: "Sandra", project: "W2D2-1", difficulty: 3, niceness: 4 },
  { name: "Sandra", project: "W2D2-2", difficulty: 2, niceness: 3 },
  { name: "Sandra", project: "W2D2-3", difficulty: 4, niceness: 3 },
  { name: "Sandra", project: "W2D3-1", difficulty: 1, niceness: 2 },
  { name: "Sandra", project: "W2D3-2", difficulty: 3, niceness: 2 },
  { name: "Sandra", project: "W2D3-3", difficulty: 2, niceness: 2 },
  { name: "Sandra", project: "W2D4-1", difficulty: 1, niceness: 3 },
  { name: "Sandra", project: "W2D4-2", difficulty: 2, niceness: 4 },
  { name: "Sandra", project: "W2D4-3", difficulty: 2, niceness: 2 },
  {
    name: "Sandra",
    project: "W2D5 - Project - Filmzoeker",
    difficulty: 2,
    niceness: 4,
  },
  { name: "Sandra", project: "W3D1-1", difficulty: 3, niceness: 3 },
  { name: "Sandra", project: "W3D1-2", difficulty: 3, niceness: 4 },
  { name: "Sandra", project: "W3D1-3", difficulty: 2, niceness: 4 },
  { name: "Sandra", project: "W3D1-4", difficulty: 2, niceness: 2 },
  { name: "Sandra", project: "W3D2-1", difficulty: 2, niceness: 4 },
  { name: "Sandra", project: "W3D2-2", difficulty: 2, niceness: 3 },
  { name: "Sandra", project: "W3D2-3", difficulty: 1, niceness: 2 },
  { name: "Sandra", project: "W3D3-1", difficulty: 1, niceness: 2 },
  { name: "Sandra", project: "W3D3-2", difficulty: 2, niceness: 2 },
  { name: "Sandra", project: "W3D3-3", difficulty: 4, niceness: 4 },
  { name: "Sandra", project: "W3D3-4", difficulty: 3, niceness: 2 },
  { name: "Sandra", project: "W3D4-1", difficulty: 2, niceness: 3 },
  { name: "Sandra", project: "W3D4-2", difficulty: 1, niceness: 1 },
  {
    name: "Sandra",
    project: "W3D5 - Project - Todo-List",
    difficulty: 1,
    niceness: 2,
  },
  { name: "Sandra", project: "W4D2-1", difficulty: 3, niceness: 3 },
  { name: "Sandra", project: "W4D2-2", difficulty: 1, niceness: 1 },
  { name: "Sandra", project: "W4D2-3", difficulty: 3, niceness: 4 },
  { name: "Sandra", project: "W4D2-4", difficulty: 1, niceness: 4 },
  { name: "Sandra", project: "W4D3-1", difficulty: 3, niceness: 1 },
  { name: "Sandra", project: "W4D3-2", difficulty: 1, niceness: 3 },
  { name: "Sandra", project: "W4D3-3", difficulty: 2, niceness: 4 },
  { name: "Sandra", project: "W4D3-4", difficulty: 1, niceness: 4 },
  { name: "Sandra", project: "W4D3-5", difficulty: 1, niceness: 3 },
  {
    name: "Sandra",
    project: "W4D3 - Project - Next-Level CSS",
    difficulty: 3,
    niceness: 4,
  },
  { name: "Sandra", project: "W5D4-1", difficulty: 1, niceness: 1 },
  {
    name: "Sandra",
    project: "W5D5 - Project - Lil_Playlist",
    difficulty: 2,
    niceness: 2,
  },
  { name: "Sandra", project: "W6D1-1", difficulty: 1, niceness: 4 },
  { name: "Sandra", project: "W6D2-1", difficulty: 2, niceness: 3 },
  {
    name: "Sandra",
    project: "W6D2 - Project - Eindopdracht",
    difficulty: 4,
    niceness: 1,
  },
  { name: "Wietske", project: "SCRUM", difficulty: 1, niceness: 1 },
  { name: "Wietske", project: "W1D1-1", difficulty: 4, niceness: 3 },
  { name: "Wietske", project: "W1D2-1", difficulty: 1, niceness: 4 },
  { name: "Wietske", project: "W1D2-2", difficulty: 1, niceness: 2 },
  { name: "Wietske", project: "W1D2-3", difficulty: 2, niceness: 3 },
  { name: "Wietske", project: "W1D2-4", difficulty: 2, niceness: 1 },
  { name: "Wietske", project: "W1D2-5", difficulty: 3, niceness: 4 },
  { name: "Wietske", project: "W1D3-1", difficulty: 1, niceness: 2 },
  { name: "Wietske", project: "W1D3-2", difficulty: 1, niceness: 4 },
  { name: "Wietske", project: "W1D3-4", difficulty: 2, niceness: 1 },
  { name: "Wietske", project: "W1D3-5", difficulty: 3, niceness: 4 },
  {
    name: "Wietske",
    project: "W1D3 - Project - Guess-the-number",
    difficulty: 2,
    niceness: 4,
  },
  { name: "Wietske", project: "W1D4-1", difficulty: 2, niceness: 4 },
  {
    name: "Wietske",
    project: "W1D4 - Project - Kleurentoggle",
    difficulty: 2,
    niceness: 3,
  },
  {
    name: "Wietske",
    project: "W1D5 - Project - Galgje",
    difficulty: 3,
    niceness: 3,
  },
  { name: "Wietske", project: "W2D1-1", difficulty: 3, niceness: 1 },
  { name: "Wietske", project: "W2D1-2", difficulty: 4, niceness: 1 },
  { name: "Wietske", project: "W2D2-1", difficulty: 2, niceness: 2 },
  { name: "Wietske", project: "W2D2-2", difficulty: 2, niceness: 4 },
  { name: "Wietske", project: "W2D2-3", difficulty: 3, niceness: 4 },
  { name: "Wietske", project: "W2D3-1", difficulty: 2, niceness: 1 },
  { name: "Wietske", project: "W2D3-2", difficulty: 1, niceness: 1 },
  { name: "Wietske", project: "W2D3-3", difficulty: 2, niceness: 3 },
  { name: "Wietske", project: "W2D4-1", difficulty: 1, niceness: 1 },
  { name: "Wietske", project: "W2D4-2", difficulty: 2, niceness: 4 },
  { name: "Wietske", project: "W2D4-3", difficulty: 4, niceness: 3 },
  {
    name: "Wietske",
    project: "W2D5 - Project - Filmzoeker",
    difficulty: 2,
    niceness: 2,
  },
  { name: "Wietske", project: "W3D1-1", difficulty: 1, niceness: 3 },
  { name: "Wietske", project: "W3D1-2", difficulty: 4, niceness: 4 },
  { name: "Wietske", project: "W3D1-3", difficulty: 4, niceness: 2 },
  { name: "Wietske", project: "W3D1-4", difficulty: 1, niceness: 4 },
  { name: "Wietske", project: "W3D2-1", difficulty: 3, niceness: 2 },
  { name: "Wietske", project: "W3D2-2", difficulty: 1, niceness: 3 },
  { name: "Wietske", project: "W3D2-3", difficulty: 2, niceness: 4 },
  { name: "Wietske", project: "W3D3-1", difficulty: 1, niceness: 4 },
  { name: "Wietske", project: "W3D3-2", difficulty: 3, niceness: 1 },
  { name: "Wietske", project: "W3D3-3", difficulty: 1, niceness: 3 },
  { name: "Wietske", project: "W3D3-4", difficulty: 3, niceness: 4 },
  { name: "Wietske", project: "W3D4-1", difficulty: 3, niceness: 4 },
  { name: "Wietske", project: "W3D4-2", difficulty: 4, niceness: 2 },
  {
    name: "Wietske",
    project: "W3D5 - Project - Todo-List",
    difficulty: 2,
    niceness: 4,
  },
  { name: "Wietske", project: "W4D2-1", difficulty: 3, niceness: 3 },
  { name: "Wietske", project: "W4D2-2", difficulty: 2, niceness: 4 },
  { name: "Wietske", project: "W4D2-3", difficulty: 1, niceness: 2 },
  { name: "Wietske", project: "W4D2-4", difficulty: 4, niceness: 3 },
  { name: "Wietske", project: "W4D3-1", difficulty: 2, niceness: 1 },
  { name: "Wietske", project: "W4D3-2", difficulty: 1, niceness: 2 },
  { name: "Wietske", project: "W4D3-3", difficulty: 1, niceness: 4 },
  { name: "Wietske", project: "W4D3-4", difficulty: 3, niceness: 4 },
  { name: "Wietske", project: "W4D3-5", difficulty: 4, niceness: 3 },
  {
    name: "Wietske",
    project: "W4D3 - Project - Next-Level CSS",
    difficulty: 4,
    niceness: 2,
  },
  { name: "Wietske", project: "W5D4-1", difficulty: 3, niceness: 1 },
  {
    name: "Wietske",
    project: "W5D5 - Project - Lil_Playlist",
    difficulty: 4,
    niceness: 2,
  },
  { name: "Wietske", project: "W6D1-1", difficulty: 1, niceness: 1 },
  { name: "Wietske", project: "W6D2-1", difficulty: 2, niceness: 1 },
  {
    name: "Wietske",
    project: "W6D2 - Project - Eindopdracht",
    difficulty: 1,
    niceness: 2,
  },
  { name: "Storm", project: "SCRUM", difficulty: 1, niceness: 1 },
  { name: "Storm", project: "W1D1-1", difficulty: 2, niceness: 2 },
  { name: "Storm", project: "W1D2-1", difficulty: 2, niceness: 3 },
  { name: "Storm", project: "W1D2-2", difficulty: 1, niceness: 3 },
  { name: "Storm", project: "W1D2-3", difficulty: 1, niceness: 2 },
  { name: "Storm", project: "W1D2-4", difficulty: 4, niceness: 3 },
  { name: "Storm", project: "W1D2-5", difficulty: 3, niceness: 3 },
  { name: "Storm", project: "W1D3-1", difficulty: 2, niceness: 3 },
  { name: "Storm", project: "W1D3-2", difficulty: 1, niceness: 1 },
  { name: "Storm", project: "W1D3-4", difficulty: 1, niceness: 1 },
  { name: "Storm", project: "W1D3-5", difficulty: 2, niceness: 2 },
  {
    name: "Storm",
    project: "W1D3 - Project - Guess-the-number",
    difficulty: 3,
    niceness: 4,
  },
  { name: "Storm", project: "W1D4-1", difficulty: 4, niceness: 2 },
  {
    name: "Storm",
    project: "W1D4 - Project - Kleurentoggle",
    difficulty: 3,
    niceness: 2,
  },
  {
    name: "Storm",
    project: "W1D5 - Project - Galgje",
    difficulty: 4,
    niceness: 4,
  },
  { name: "Storm", project: "W2D1-1", difficulty: 2, niceness: 4 },
  { name: "Storm", project: "W2D1-2", difficulty: 3, niceness: 2 },
  { name: "Storm", project: "W2D2-1", difficulty: 4, niceness: 4 },
  { name: "Storm", project: "W2D2-2", difficulty: 2, niceness: 1 },
  { name: "Storm", project: "W2D2-3", difficulty: 1, niceness: 1 },
  { name: "Storm", project: "W2D3-1", difficulty: 2, niceness: 3 },
  { name: "Storm", project: "W2D3-2", difficulty: 3, niceness: 4 },
  { name: "Storm", project: "W2D3-3", difficulty: 3, niceness: 2 },
  { name: "Storm", project: "W2D4-1", difficulty: 3, niceness: 4 },
  { name: "Storm", project: "W2D4-2", difficulty: 4, niceness: 3 },
  { name: "Storm", project: "W2D4-3", difficulty: 2, niceness: 1 },
  {
    name: "Storm",
    project: "W2D5 - Project - Filmzoeker",
    difficulty: 4,
    niceness: 1,
  },
  { name: "Storm", project: "W3D1-1", difficulty: 2, niceness: 1 },
  { name: "Storm", project: "W3D1-2", difficulty: 2, niceness: 2 },
  { name: "Storm", project: "W3D1-3", difficulty: 1, niceness: 2 },
  { name: "Storm", project: "W3D1-4", difficulty: 2, niceness: 3 },
  { name: "Storm", project: "W3D2-1", difficulty: 1, niceness: 4 },
  { name: "Storm", project: "W3D2-2", difficulty: 3, niceness: 3 },
  { name: "Storm", project: "W3D2-3", difficulty: 3, niceness: 4 },
  { name: "Storm", project: "W3D3-1", difficulty: 3, niceness: 4 },
  { name: "Storm", project: "W3D3-2", difficulty: 1, niceness: 2 },
  { name: "Storm", project: "W3D3-3", difficulty: 3, niceness: 1 },
  { name: "Storm", project: "W3D3-4", difficulty: 3, niceness: 1 },
  { name: "Storm", project: "W3D4-1", difficulty: 2, niceness: 4 },
  { name: "Storm", project: "W3D4-2", difficulty: 3, niceness: 4 },
  {
    name: "Storm",
    project: "W3D5 - Project - Todo-List",
    difficulty: 3,
    niceness: 2,
  },
  { name: "Storm", project: "W4D2-1", difficulty: 2, niceness: 1 },
  { name: "Storm", project: "W4D2-2", difficulty: 3, niceness: 3 },
  { name: "Storm", project: "W4D2-3", difficulty: 2, niceness: 2 },
  { name: "Storm", project: "W4D2-4", difficulty: 3, niceness: 4 },
  { name: "Storm", project: "W4D3-1", difficulty: 3, niceness: 4 },
  { name: "Storm", project: "W4D3-2", difficulty: 2, niceness: 3 },
  { name: "Storm", project: "W4D3-3", difficulty: 1, niceness: 1 },
  { name: "Storm", project: "W4D3-4", difficulty: 3, niceness: 1 },
  { name: "Storm", project: "W4D3-5", difficulty: 2, niceness: 3 },
  {
    name: "Storm",
    project: "W4D3 - Project - Next-Level CSS",
    difficulty: 4,
    niceness: 1,
  },
  { name: "Storm", project: "W5D4-1", difficulty: 2, niceness: 2 },
  {
    name: "Storm",
    project: "W5D5 - Project - Lil_Playlist",
    difficulty: 1,
    niceness: 2,
  },
  { name: "Storm", project: "W6D1-1", difficulty: 4, niceness: 4 },
  { name: "Storm", project: "W6D2-1", difficulty: 1, niceness: 1 },
  {
    name: "Storm",
    project: "W6D2 - Project - Eindopdracht",
    difficulty: 3,
    niceness: 3,
  },
];

const studentProfiles = [
  {
    first_name: "Evelyn",
    last_name: "Scheffler",
    date_of_birth: "1996-11-02T17:59:18.176Z",
    email: "evelyn.scheffler@wincacademy.nl",
    picture: {
      large: "https://randomuser.me/api/portraits/women/50.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/50.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/50.jpg",
    },
  },
  {
    first_name: "Aranka",
    last_name: "Rasmussen",
    date_of_birth: "1992-04-11T10:14:34.583Z",
    email: "aranka.rasmussen@wincacademy.nl",
    picture: {
      large: "https://randomuser.me/api/portraits/women/94.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/94.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/94.jpg",
    },
  },
  {
    first_name: "Floris",
    last_name: "Hart",
    date_of_birth: "1997-09-05T16:24:07.307Z",
    email: "floris.hart@wincacademy.nl",
    picture: {
      large: "https://randomuser.me/api/portraits/men/35.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/35.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/35.jpg",
    },
  },
  {
    first_name: "Hector",
    last_name: "Giraud",
    date_of_birth: "1997-11-18T05:47:37.006Z",
    email: "hector.giraud@wincacademy.nl",
    picture: {
      large: "https://randomuser.me/api/portraits/men/53.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/53.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/53.jpg",
    },
  },
  {
    first_name: "Martina",
    last_name: "Kim",
    date_of_birth: "1996-06-11T22:06:03.079Z",
    email: "martina.kim@wincacademy.nl",
    picture: {
      large: "https://randomuser.me/api/portraits/women/21.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/21.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/21.jpg",
    },
  },
  {
    first_name: "Maurits",
    last_name: "Hamre",
    date_of_birth: "1998-05-25T05:07:35.054Z",
    email: "maurits.hamre@wincacademy.nl",
    picture: {
      large: "https://randomuser.me/api/portraits/men/5.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/5.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/5.jpg",
    },
  },
  {
    first_name: "Rahima",
    last_name: "Porter",
    date_of_birth: "1996-05-01T15:22:10.168Z",
    email: "rahima.porter@wincacademy.nl",
    picture: {
      large: "https://randomuser.me/api/portraits/women/23.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/23.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/23.jpg",
    },
  },
  {
    first_name: "Sandra",
    last_name: "Hayes",
    date_of_birth: "1995-09-23T17:24:21.230Z",
    email: "sandra.hayes@wincacademy.nl",
    picture: {
      large: "https://randomuser.me/api/portraits/women/48.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/48.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/48.jpg",
    },
  },
  {
    first_name: "Wietske",
    last_name: "Johansen",
    date_of_birth: "1996-06-07T20:19:00.289Z",
    email: "wietske.johansen@wincacademy.nl",
    picture: {
      large: "https://randomuser.me/api/portraits/men/2.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/2.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/2.jpg",
    },
  },
  {
    first_name: "Storm",
    last_name: "Ramos",
    date_of_birth: "1992-11-22T05:58:33.685Z",
    email: "storm.ramos@wincacademy.nl",
    picture: {
      large: "https://randomuser.me/api/portraits/women/24.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/24.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/24.jpg",
    },
  },
];

const data = {
  studentData: studentData,
  studentProfiles: studentProfiles,
};

export { data };
