const studentData = [
{"name":"Evelyn","project":"SCRUM","dificulty":"3","niceness":"4"},
{"name":"Evelyn","project":"W1D1-1","dificulty":"3","niceness":"3"},
{"name":"Evelyn","project":"W1D2-1","dificulty":"1","niceness":"3"},
{"name":"Evelyn","project":"W1D2-2","dificulty":"1","niceness":"4"},
{"name":"Evelyn","project":"W1D2-3","dificulty":"2","niceness":"3"},
{"name":"Evelyn","project":"W1D2-4","dificulty":"3","niceness":"4"},
{"name":"Evelyn","project":"W1D2-5","dificulty":"3","niceness":"4"},
{"name":"Evelyn","project":"W1D3-1","dificulty":"3","niceness":"4"},
{"name":"Evelyn","project":"W1D3-2","dificulty":"3","niceness":"4"},
{"name":"Evelyn","project":"W1D3-4","dificulty":"4","niceness":"4"},
{"name":"Evelyn","project":"W1D3-5","dificulty":"4","niceness":"4"},
{"name":"Evelyn","project":"W1D3 - Project - Guess-the-number","dificulty":"5","niceness":"5"},
{"name":"Evelyn","project":"W1D4-1","dificulty":"4","niceness":"5"},
{"name":"Evelyn","project":"W1D4 - Project - Kleurentoggle","dificulty":"3","niceness":"4"},
{"name":"Evelyn","project":"W1D5 - Project - Galgje","dificulty":"3","niceness":"3"}
,
{"name":"Evelyn","project":"W2D1-1","dificulty":"1","niceness":"5"},
{"name":"Evelyn","project":"W2D1-2","dificulty":"2","niceness":"5"},
{"name":"Evelyn","project":"W2D2-1","dificulty":"3","niceness":"4"},
{"name":"Evelyn","project":"W2D2-2","dificulty":"3","niceness":"4"},
{"name":"Evelyn","project":"W2D2-3","dificulty":"3","niceness":"4"},
{"name":"Evelyn","project":"W2D3-1","dificulty":"4","niceness":"4"},
{"name":"Evelyn","project":"W2D3-2","dificulty":"1","niceness":"3"},
{"name":"Evelyn","project":"W2D3-3","dificulty":"4","niceness":"4"},
{"name":"Evelyn","project":"W2D4-1","dificulty":"1","niceness":"3"},
{"name":"Evelyn","project":"W2D4-2","dificulty":"4","niceness":"4"},
{"name":"Evelyn","project":"W2D4-3","dificulty":"1","niceness":"3"},
{"name":"Evelyn","project":"W2D5 - Project - Filmzoeker","dificulty":"3","niceness":"4"},
{"name":"Evelyn","project":"W3D1-1","dificulty":"3","niceness":"4"},
{"name":"Evelyn","project":"W3D1-2","dificulty":"2","niceness":"4"},
{"name":"Evelyn","project":"W3D1-3","dificulty":"3","niceness":"4"},
{"name":"Evelyn","project":"W3D1-4","dificulty":"3","niceness":"3"},
{"name":"Evelyn","project":"W3D2-1","dificulty":"2","niceness":"4"},
{"name":"Evelyn","project":"W3D2-2","dificulty":"3","niceness":"3"},
{"name":"Evelyn","project":"W3D2-3","dificulty":"3","niceness":"5"},
{"name":"Evelyn","project":"W3D3-1","dificulty":"4","niceness":"4"},
{"name":"Evelyn","project":"W3D3-2","dificulty":"4","niceness":"5"},
{"name":"Evelyn","project":"W3D3-3","dificulty":"3","niceness":"5"},
{"name":"Evelyn","project":"W3D3-4","dificulty":"4","niceness":"5"},
{"name":"Evelyn","project":"W3D4-1","dificulty":"5","niceness":"5"},
{"name":"Evelyn","project":"W3D4-2","dificulty":"1","niceness":"5"},
{"name":"Evelyn","project":"W3D5 - Project - Todo-List","dificulty":"2","niceness":"5"},
{"name":"Evelyn","project":"W4D2-1","dificulty":"1","niceness":"5"},
{"name":"Evelyn","project":"W4D2-2","dificulty":"1","niceness":"5"},
{"name":"Evelyn","project":"W4D2-3","dificulty":"1","niceness":"5"},
{"name":"Evelyn","project":"W4D2-4","dificulty":"1","niceness":"5"},
{"name":"Evelyn","project":"W4D3-1","dificulty":"1","niceness":"5"},
{"name":"Evelyn","project":"W4D3-2","dificulty":"1","niceness":"5"},
{"name":"Evelyn","project":"W4D3-3","dificulty":"1","niceness":"5"},
{"name":"Evelyn","project":"W4D3-4","dificulty":"1","niceness":"5"},
{"name":"Evelyn","project":"W4D3-5","dificulty":"1","niceness":"5"},
{"name":"Evelyn","project":"W4D3 - Project - Next-Level CSS","dificulty":"1","niceness":"5"},
{"name":"Evelyn","project":"W5D4-1","dificulty":"3","niceness":"4"},
{"name":"Evelyn","project":"W5D5 - Project - Lil_Playlist","dificulty":"4","niceness":"3"},
{"name":"Evelyn","project":"W6D1-1","dificulty":"5","niceness":"5"},
{"name":"Evelyn","project":"W6D2-1","dificulty":"4","niceness":"3"},
{"name":"Evelyn","project":"W6D2 - Project - Eindopdracht","dificulty":"5","niceness":"5"},
{"name":"Aranka","project":"SCRUM","dificulty":"1","niceness":"1"},
{"name":"Aranka","project":"W1D1-1","dificulty":"4","niceness":"3"},
{"name":"Aranka","project":"W1D2-1","dificulty":"3","niceness":"1"},
{"name":"Aranka","project":"W1D2-2","dificulty":"3","niceness":"2"},
{"name":"Aranka","project":"W1D2-3","dificulty":"4","niceness":"1"},
{"name":"Aranka","project":"W1D2-4","dificulty":"2","niceness":"3"},
{"name":"Aranka","project":"W1D2-5","dificulty":"4","niceness":"2"},
{"name":"Aranka","project":"W1D3-1","dificulty":"3","niceness":"2"},
{"name":"Aranka","project":"W1D3-2","dificulty":"2","niceness":"1"},
{"name":"Aranka","project":"W1D3-4","dificulty":"1","niceness":"2"},
{"name":"Aranka","project":"W1D3-5","dificulty":"4","niceness":"1"},
{"name":"Aranka","project":"W1D3 - Project - Guess-the-number","dificulty":"2","niceness":"3"},
{"name":"Aranka","project":"W1D4-1","dificulty":"3","niceness":"2"},
{"name":"Aranka","project":"W1D4 - Project - Kleurentoggle","dificulty":"4","niceness":"3"},
{"name":"Aranka","project":"W1D5 - Project - Galgje","dificulty":"4","niceness":"1"}
,
{"name":"Aranka","project":"W2D1-1","dificulty":"2","niceness":"4"},
{"name":"Aranka","project":"W2D1-2","dificulty":"4","niceness":"4"},
{"name":"Aranka","project":"W2D2-1","dificulty":"3","niceness":"4"},
{"name":"Aranka","project":"W2D2-2","dificulty":"3","niceness":"4"},
{"name":"Aranka","project":"W2D2-3","dificulty":"1","niceness":"4"},
{"name":"Aranka","project":"W2D3-1","dificulty":"4","niceness":"3"},
{"name":"Aranka","project":"W2D3-2","dificulty":"4","niceness":"1"},
{"name":"Aranka","project":"W2D3-3","dificulty":"1","niceness":"1"},
{"name":"Aranka","project":"W2D4-1","dificulty":"1","niceness":"4"},
{"name":"Aranka","project":"W2D4-2","dificulty":"2","niceness":"3"},
{"name":"Aranka","project":"W2D4-3","dificulty":"2","niceness":"3"},
{"name":"Aranka","project":"W2D5 - Project - Filmzoeker","dificulty":"2","niceness":"2"},
{"name":"Aranka","project":"W3D1-1","dificulty":"4","niceness":"2"},
{"name":"Aranka","project":"W3D1-2","dificulty":"3","niceness":"2"},
{"name":"Aranka","project":"W3D1-3","dificulty":"1","niceness":"4"},
{"name":"Aranka","project":"W3D1-4","dificulty":"1","niceness":"3"},
{"name":"Aranka","project":"W3D2-1","dificulty":"1","niceness":"3"},
{"name":"Aranka","project":"W3D2-2","dificulty":"2","niceness":"3"},
{"name":"Aranka","project":"W3D2-3","dificulty":"2","niceness":"3"},
{"name":"Aranka","project":"W3D3-1","dificulty":"2","niceness":"2"},
{"name":"Aranka","project":"W3D3-2","dificulty":"4","niceness":"3"},
{"name":"Aranka","project":"W3D3-3","dificulty":"3","niceness":"3"},
{"name":"Aranka","project":"W3D3-4","dificulty":"1","niceness":"3"},
{"name":"Aranka","project":"W3D4-1","dificulty":"1","niceness":"1"},
{"name":"Aranka","project":"W3D4-2","dificulty":"3","niceness":"2"},
{"name":"Aranka","project":"W3D5 - Project - Todo-List","dificulty":"1","niceness":"1"},
{"name":"Aranka","project":"W4D2-1","dificulty":"2","niceness":"1"},
{"name":"Aranka","project":"W4D2-2","dificulty":"3","niceness":"2"},
{"name":"Aranka","project":"W4D2-3","dificulty":"2","niceness":"2"},
{"name":"Aranka","project":"W4D2-4","dificulty":"3","niceness":"4"},
{"name":"Aranka","project":"W4D3-1","dificulty":"2","niceness":"1"},
{"name":"Aranka","project":"W4D3-2","dificulty":"4","niceness":"4"},
{"name":"Aranka","project":"W4D3-3","dificulty":"3","niceness":"1"},
{"name":"Aranka","project":"W4D3-4","dificulty":"3","niceness":"1"},
{"name":"Aranka","project":"W4D3-5","dificulty":"4","niceness":"3"},
{"name":"Aranka","project":"W4D3 - Project - Next-Level CSS","dificulty":"4","niceness":"4"},
{"name":"Aranka","project":"W5D4-1","dificulty":"1","niceness":"3"},
{"name":"Aranka","project":"W5D5 - Project - Lil_Playlist","dificulty":"3","niceness":"2"},
{"name":"Aranka","project":"W6D1-1","dificulty":"1","niceness":"1"},
{"name":"Aranka","project":"W6D2-1","dificulty":"2","niceness":"2"},
{"name":"Aranka","project":"W6D2 - Project - Eindopdracht","dificulty":"3","niceness":"4"},
{"name":"Floris","project":"SCRUM","dificulty":"2","niceness":"1"},
{"name":"Floris","project":"W1D1-1","dificulty":"4","niceness":"3"},
{"name":"Floris","project":"W1D2-1","dificulty":"1","niceness":"2"},
{"name":"Floris","project":"W1D2-2","dificulty":"1","niceness":"4"},
{"name":"Floris","project":"W1D2-3","dificulty":"1","niceness":"4"},
{"name":"Floris","project":"W1D2-4","dificulty":"3","niceness":"4"},
{"name":"Floris","project":"W1D2-5","dificulty":"1","niceness":"3"},
{"name":"Floris","project":"W1D3-1","dificulty":"2","niceness":"4"},
{"name":"Floris","project":"W1D3-2","dificulty":"4","niceness":"4"},
{"name":"Floris","project":"W1D3-4","dificulty":"4","niceness":"2"},
{"name":"Floris","project":"W1D3-5","dificulty":"2","niceness":"4"},
{"name":"Floris","project":"W1D3 - Project - Guess-the-number","dificulty":"2","niceness":"2"},
{"name":"Floris","project":"W1D4-1","dificulty":"1","niceness":"3"},
{"name":"Floris","project":"W1D4 - Project - Kleurentoggle","dificulty":"4","niceness":"3"},
{"name":"Floris","project":"W1D5 - Project - Galgje","dificulty":"4","niceness":"4"}
,
{"name":"Floris","project":"W2D1-1","dificulty":"2","niceness":"2"},
{"name":"Floris","project":"W2D1-2","dificulty":"4","niceness":"1"},
{"name":"Floris","project":"W2D2-1","dificulty":"4","niceness":"1"},
{"name":"Floris","project":"W2D2-2","dificulty":"2","niceness":"2"},
{"name":"Floris","project":"W2D2-3","dificulty":"4","niceness":"2"},
{"name":"Floris","project":"W2D3-1","dificulty":"1","niceness":"1"},
{"name":"Floris","project":"W2D3-2","dificulty":"1","niceness":"2"},
{"name":"Floris","project":"W2D3-3","dificulty":"3","niceness":"3"},
{"name":"Floris","project":"W2D4-1","dificulty":"4","niceness":"4"},
{"name":"Floris","project":"W2D4-2","dificulty":"3","niceness":"1"},
{"name":"Floris","project":"W2D4-3","dificulty":"4","niceness":"1"},
{"name":"Floris","project":"W2D5 - Project - Filmzoeker","dificulty":"4","niceness":"1"},
{"name":"Floris","project":"W3D1-1","dificulty":"4","niceness":"3"},
{"name":"Floris","project":"W3D1-2","dificulty":"2","niceness":"3"},
{"name":"Floris","project":"W3D1-3","dificulty":"2","niceness":"3"},
{"name":"Floris","project":"W3D1-4","dificulty":"3","niceness":"3"},
{"name":"Floris","project":"W3D2-1","dificulty":"3","niceness":"2"},
{"name":"Floris","project":"W3D2-2","dificulty":"2","niceness":"2"},
{"name":"Floris","project":"W3D2-3","dificulty":"3","niceness":"2"},
{"name":"Floris","project":"W3D3-1","dificulty":"4","niceness":"4"},
{"name":"Floris","project":"W3D3-2","dificulty":"2","niceness":"4"},
{"name":"Floris","project":"W3D3-3","dificulty":"2","niceness":"1"},
{"name":"Floris","project":"W3D3-4","dificulty":"3","niceness":"2"},
{"name":"Floris","project":"W3D4-1","dificulty":"1","niceness":"3"},
{"name":"Floris","project":"W3D4-2","dificulty":"2","niceness":"2"},
{"name":"Floris","project":"W3D5 - Project - Todo-List","dificulty":"4","niceness":"2"},
{"name":"Floris","project":"W4D2-1","dificulty":"1","niceness":"4"},
{"name":"Floris","project":"W4D2-2","dificulty":"2","niceness":"3"},
{"name":"Floris","project":"W4D2-3","dificulty":"2","niceness":"4"},
{"name":"Floris","project":"W4D2-4","dificulty":"1","niceness":"2"},
{"name":"Floris","project":"W4D3-1","dificulty":"1","niceness":"4"},
{"name":"Floris","project":"W4D3-2","dificulty":"4","niceness":"4"},
{"name":"Floris","project":"W4D3-3","dificulty":"3","niceness":"2"},
{"name":"Floris","project":"W4D3-4","dificulty":"2","niceness":"2"},
{"name":"Floris","project":"W4D3-5","dificulty":"4","niceness":"1"},
{"name":"Floris","project":"W4D3 - Project - Next-Level CSS","dificulty":"2","niceness":"2"},
{"name":"Floris","project":"W5D4-1","dificulty":"1","niceness":"3"},
{"name":"Floris","project":"W5D5 - Project - Lil_Playlist","dificulty":"3","niceness":"1"},
{"name":"Floris","project":"W6D1-1","dificulty":"3","niceness":"2"},
{"name":"Floris","project":"W6D2-1","dificulty":"1","niceness":"1"},
{"name":"Floris","project":"W6D2 - Project - Eindopdracht","dificulty":"4","niceness":"1"},
{"name":"Hector","project":"SCRUM","dificulty":"1","niceness":"2"},
{"name":"Hector","project":"W1D1-1","dificulty":"1","niceness":"4"},
{"name":"Hector","project":"W1D2-1","dificulty":"2","niceness":"4"},
{"name":"Hector","project":"W1D2-2","dificulty":"2","niceness":"3"},
{"name":"Hector","project":"W1D2-3","dificulty":"1","niceness":"2"},
{"name":"Hector","project":"W1D2-4","dificulty":"1","niceness":"3"},
{"name":"Hector","project":"W1D2-5","dificulty":"3","niceness":"1"},
{"name":"Hector","project":"W1D3-1","dificulty":"1","niceness":"4"},
{"name":"Hector","project":"W1D3-2","dificulty":"4","niceness":"3"},
{"name":"Hector","project":"W1D3-4","dificulty":"3","niceness":"1"},
{"name":"Hector","project":"W1D3-5","dificulty":"4","niceness":"2"},
{"name":"Hector","project":"W1D3 - Project - Guess-the-number","dificulty":"3","niceness":"1"},
{"name":"Hector","project":"W1D4-1","dificulty":"1","niceness":"1"},
{"name":"Hector","project":"W1D4 - Project - Kleurentoggle","dificulty":"1","niceness":"3"},
{"name":"Hector","project":"W1D5 - Project - Galgje","dificulty":"2","niceness":"4"}
,
{"name":"Hector","project":"W2D1-1","dificulty":"4","niceness":"4"},
{"name":"Hector","project":"W2D1-2","dificulty":"3","niceness":"2"},
{"name":"Hector","project":"W2D2-1","dificulty":"4","niceness":"3"},
{"name":"Hector","project":"W2D2-2","dificulty":"1","niceness":"2"},
{"name":"Hector","project":"W2D2-3","dificulty":"3","niceness":"2"},
{"name":"Hector","project":"W2D3-1","dificulty":"3","niceness":"1"},
{"name":"Hector","project":"W2D3-2","dificulty":"4","niceness":"2"},
{"name":"Hector","project":"W2D3-3","dificulty":"4","niceness":"2"},
{"name":"Hector","project":"W2D4-1","dificulty":"2","niceness":"4"},
{"name":"Hector","project":"W2D4-2","dificulty":"4","niceness":"1"},
{"name":"Hector","project":"W2D4-3","dificulty":"3","niceness":"2"},
{"name":"Hector","project":"W2D5 - Project - Filmzoeker","dificulty":"4","niceness":"1"},
{"name":"Hector","project":"W3D1-1","dificulty":"1","niceness":"1"},
{"name":"Hector","project":"W3D1-2","dificulty":"1","niceness":"4"},
{"name":"Hector","project":"W3D1-3","dificulty":"3","niceness":"2"},
{"name":"Hector","project":"W3D1-4","dificulty":"4","niceness":"3"},
{"name":"Hector","project":"W3D2-1","dificulty":"1","niceness":"3"},
{"name":"Hector","project":"W3D2-2","dificulty":"4","niceness":"3"},
{"name":"Hector","project":"W3D2-3","dificulty":"2","niceness":"1"},
{"name":"Hector","project":"W3D3-1","dificulty":"4","niceness":"4"},
{"name":"Hector","project":"W3D3-2","dificulty":"3","niceness":"1"},
{"name":"Hector","project":"W3D3-3","dificulty":"2","niceness":"4"},
{"name":"Hector","project":"W3D3-4","dificulty":"4","niceness":"1"},
{"name":"Hector","project":"W3D4-1","dificulty":"3","niceness":"4"},
{"name":"Hector","project":"W3D4-2","dificulty":"1","niceness":"4"},
{"name":"Hector","project":"W3D5 - Project - Todo-List","dificulty":"2","niceness":"4"},
{"name":"Hector","project":"W4D2-1","dificulty":"1","niceness":"1"},
{"name":"Hector","project":"W4D2-2","dificulty":"2","niceness":"1"},
{"name":"Hector","project":"W4D2-3","dificulty":"3","niceness":"3"},
{"name":"Hector","project":"W4D2-4","dificulty":"1","niceness":"3"},
{"name":"Hector","project":"W4D3-1","dificulty":"3","niceness":"3"},
{"name":"Hector","project":"W4D3-2","dificulty":"1","niceness":"4"},
{"name":"Hector","project":"W4D3-3","dificulty":"3","niceness":"1"},
{"name":"Hector","project":"W4D3-4","dificulty":"1","niceness":"3"},
{"name":"Hector","project":"W4D3-5","dificulty":"1","niceness":"2"},
{"name":"Hector","project":"W4D3 - Project - Next-Level CSS","dificulty":"3","niceness":"1"},
{"name":"Hector","project":"W5D4-1","dificulty":"3","niceness":"4"},
{"name":"Hector","project":"W5D5 - Project - Lil_Playlist","dificulty":"3","niceness":"1"},
{"name":"Hector","project":"W6D1-1","dificulty":"1","niceness":"1"},
{"name":"Hector","project":"W6D2-1","dificulty":"4","niceness":"2"},
{"name":"Hector","project":"W6D2 - Project - Eindopdracht","dificulty":"2","niceness":"4"},
{"name":"Martina","project":"SCRUM","dificulty":"1","niceness":"1"},
{"name":"Martina","project":"W1D1-1","dificulty":"4","niceness":"1"},
{"name":"Martina","project":"W1D2-1","dificulty":"3","niceness":"3"},
{"name":"Martina","project":"W1D2-2","dificulty":"2","niceness":"1"},
{"name":"Martina","project":"W1D2-3","dificulty":"2","niceness":"1"},
{"name":"Martina","project":"W1D2-4","dificulty":"4","niceness":"2"},
{"name":"Martina","project":"W1D2-5","dificulty":"3","niceness":"4"},
{"name":"Martina","project":"W1D3-1","dificulty":"3","niceness":"4"},
{"name":"Martina","project":"W1D3-2","dificulty":"2","niceness":"1"},
{"name":"Martina","project":"W1D3-4","dificulty":"3","niceness":"2"},
{"name":"Martina","project":"W1D3-5","dificulty":"1","niceness":"1"},
{"name":"Martina","project":"W1D3 - Project - Guess-the-number","dificulty":"2","niceness":"2"},
{"name":"Martina","project":"W1D4-1","dificulty":"4","niceness":"2"},
{"name":"Martina","project":"W1D4 - Project - Kleurentoggle","dificulty":"1","niceness":"3"},
{"name":"Martina","project":"W1D5 - Project - Galgje","dificulty":"1","niceness":"4"}
,
{"name":"Martina","project":"W2D1-1","dificulty":"1","niceness":"4"},
{"name":"Martina","project":"W2D1-2","dificulty":"4","niceness":"2"},
{"name":"Martina","project":"W2D2-1","dificulty":"4","niceness":"1"},
{"name":"Martina","project":"W2D2-2","dificulty":"3","niceness":"3"},
{"name":"Martina","project":"W2D2-3","dificulty":"3","niceness":"1"},
{"name":"Martina","project":"W2D3-1","dificulty":"4","niceness":"2"},
{"name":"Martina","project":"W2D3-2","dificulty":"3","niceness":"4"},
{"name":"Martina","project":"W2D3-3","dificulty":"3","niceness":"3"},
{"name":"Martina","project":"W2D4-1","dificulty":"1","niceness":"4"},
{"name":"Martina","project":"W2D4-2","dificulty":"3","niceness":"4"},
{"name":"Martina","project":"W2D4-3","dificulty":"3","niceness":"4"},
{"name":"Martina","project":"W2D5 - Project - Filmzoeker","dificulty":"2","niceness":"4"},
{"name":"Martina","project":"W3D1-1","dificulty":"1","niceness":"1"},
{"name":"Martina","project":"W3D1-2","dificulty":"3","niceness":"3"},
{"name":"Martina","project":"W3D1-3","dificulty":"3","niceness":"1"},
{"name":"Martina","project":"W3D1-4","dificulty":"3","niceness":"2"},
{"name":"Martina","project":"W3D2-1","dificulty":"1","niceness":"2"},
{"name":"Martina","project":"W3D2-2","dificulty":"2","niceness":"4"},
{"name":"Martina","project":"W3D2-3","dificulty":"3","niceness":"1"},
{"name":"Martina","project":"W3D3-1","dificulty":"1","niceness":"4"},
{"name":"Martina","project":"W3D3-2","dificulty":"4","niceness":"1"},
{"name":"Martina","project":"W3D3-3","dificulty":"3","niceness":"3"},
{"name":"Martina","project":"W3D3-4","dificulty":"2","niceness":"3"},
{"name":"Martina","project":"W3D4-1","dificulty":"4","niceness":"4"},
{"name":"Martina","project":"W3D4-2","dificulty":"3","niceness":"1"},
{"name":"Martina","project":"W3D5 - Project - Todo-List","dificulty":"2","niceness":"3"},
{"name":"Martina","project":"W4D2-1","dificulty":"3","niceness":"4"},
{"name":"Martina","project":"W4D2-2","dificulty":"1","niceness":"2"},
{"name":"Martina","project":"W4D2-3","dificulty":"3","niceness":"4"},
{"name":"Martina","project":"W4D2-4","dificulty":"4","niceness":"1"},
{"name":"Martina","project":"W4D3-1","dificulty":"2","niceness":"4"},
{"name":"Martina","project":"W4D3-2","dificulty":"1","niceness":"3"},
{"name":"Martina","project":"W4D3-3","dificulty":"2","niceness":"4"},
{"name":"Martina","project":"W4D3-4","dificulty":"4","niceness":"1"},
{"name":"Martina","project":"W4D3-5","dificulty":"3","niceness":"2"},
{"name":"Martina","project":"W4D3 - Project - Next-Level CSS","dificulty":"3","niceness":"4"},
{"name":"Martina","project":"W5D4-1","dificulty":"1","niceness":"4"},
{"name":"Martina","project":"W5D5 - Project - Lil_Playlist","dificulty":"1","niceness":"1"},
{"name":"Martina","project":"W6D1-1","dificulty":"2","niceness":"1"},
{"name":"Martina","project":"W6D2-1","dificulty":"1","niceness":"4"},
{"name":"Martina","project":"W6D2 - Project - Eindopdracht","dificulty":"1","niceness":"4"},
{"name":"Maurits","project":"SCRUM","dificulty":"3","niceness":"4"},
{"name":"Maurits","project":"W1D1-1","dificulty":"4","niceness":"3"},
{"name":"Maurits","project":"W1D2-1","dificulty":"2","niceness":"2"},
{"name":"Maurits","project":"W1D2-2","dificulty":"1","niceness":"4"},
{"name":"Maurits","project":"W1D2-3","dificulty":"2","niceness":"2"},
{"name":"Maurits","project":"W1D2-4","dificulty":"3","niceness":"1"},
{"name":"Maurits","project":"W1D2-5","dificulty":"2","niceness":"3"},
{"name":"Maurits","project":"W1D3-1","dificulty":"2","niceness":"4"},
{"name":"Maurits","project":"W1D3-2","dificulty":"2","niceness":"2"},
{"name":"Maurits","project":"W1D3-4","dificulty":"2","niceness":"2"},
{"name":"Maurits","project":"W1D3-5","dificulty":"1","niceness":"3"},
{"name":"Maurits","project":"W1D3 - Project - Guess-the-number","dificulty":"1","niceness":"1"},
{"name":"Maurits","project":"W1D4-1","dificulty":"3","niceness":"4"},
{"name":"Maurits","project":"W1D4 - Project - Kleurentoggle","dificulty":"4","niceness":"1"},
{"name":"Maurits","project":"W1D5 - Project - Galgje","dificulty":"3","niceness":"2"}
,
{"name":"Maurits","project":"W2D1-1","dificulty":"1","niceness":"1"},
{"name":"Maurits","project":"W2D1-2","dificulty":"2","niceness":"3"},
{"name":"Maurits","project":"W2D2-1","dificulty":"1","niceness":"2"},
{"name":"Maurits","project":"W2D2-2","dificulty":"4","niceness":"1"},
{"name":"Maurits","project":"W2D2-3","dificulty":"2","niceness":"2"},
{"name":"Maurits","project":"W2D3-1","dificulty":"2","niceness":"2"},
{"name":"Maurits","project":"W2D3-2","dificulty":"3","niceness":"3"},
{"name":"Maurits","project":"W2D3-3","dificulty":"2","niceness":"1"},
{"name":"Maurits","project":"W2D4-1","dificulty":"1","niceness":"3"},
{"name":"Maurits","project":"W2D4-2","dificulty":"3","niceness":"2"},
{"name":"Maurits","project":"W2D4-3","dificulty":"3","niceness":"3"},
{"name":"Maurits","project":"W2D5 - Project - Filmzoeker","dificulty":"3","niceness":"1"},
{"name":"Maurits","project":"W3D1-1","dificulty":"4","niceness":"4"},
{"name":"Maurits","project":"W3D1-2","dificulty":"1","niceness":"3"},
{"name":"Maurits","project":"W3D1-3","dificulty":"1","niceness":"4"},
{"name":"Maurits","project":"W3D1-4","dificulty":"1","niceness":"2"},
{"name":"Maurits","project":"W3D2-1","dificulty":"1","niceness":"4"},
{"name":"Maurits","project":"W3D2-2","dificulty":"1","niceness":"1"},
{"name":"Maurits","project":"W3D2-3","dificulty":"4","niceness":"3"},
{"name":"Maurits","project":"W3D3-1","dificulty":"1","niceness":"1"},
{"name":"Maurits","project":"W3D3-2","dificulty":"2","niceness":"1"},
{"name":"Maurits","project":"W3D3-3","dificulty":"1","niceness":"3"},
{"name":"Maurits","project":"W3D3-4","dificulty":"4","niceness":"1"},
{"name":"Maurits","project":"W3D4-1","dificulty":"4","niceness":"4"},
{"name":"Maurits","project":"W3D4-2","dificulty":"1","niceness":"3"},
{"name":"Maurits","project":"W3D5 - Project - Todo-List","dificulty":"3","niceness":"4"},
{"name":"Maurits","project":"W4D2-1","dificulty":"3","niceness":"1"},
{"name":"Maurits","project":"W4D2-2","dificulty":"4","niceness":"4"},
{"name":"Maurits","project":"W4D2-3","dificulty":"4","niceness":"1"},
{"name":"Maurits","project":"W4D2-4","dificulty":"2","niceness":"3"},
{"name":"Maurits","project":"W4D3-1","dificulty":"3","niceness":"1"},
{"name":"Maurits","project":"W4D3-2","dificulty":"3","niceness":"2"},
{"name":"Maurits","project":"W4D3-3","dificulty":"3","niceness":"4"},
{"name":"Maurits","project":"W4D3-4","dificulty":"1","niceness":"3"},
{"name":"Maurits","project":"W4D3-5","dificulty":"2","niceness":"1"},
{"name":"Maurits","project":"W4D3 - Project - Next-Level CSS","dificulty":"2","niceness":"3"},
{"name":"Maurits","project":"W5D4-1","dificulty":"1","niceness":"3"},
{"name":"Maurits","project":"W5D5 - Project - Lil_Playlist","dificulty":"4","niceness":"2"},
{"name":"Maurits","project":"W6D1-1","dificulty":"1","niceness":"3"},
{"name":"Maurits","project":"W6D2-1","dificulty":"1","niceness":"4"},
{"name":"Maurits","project":"W6D2 - Project - Eindopdracht","dificulty":"3","niceness":"3"},
{"name":"Rahima","project":"SCRUM","dificulty":"2","niceness":"4"},
{"name":"Rahima","project":"W1D1-1","dificulty":"3","niceness":"4"},
{"name":"Rahima","project":"W1D2-1","dificulty":"2","niceness":"4"},
{"name":"Rahima","project":"W1D2-2","dificulty":"1","niceness":"2"},
{"name":"Rahima","project":"W1D2-3","dificulty":"1","niceness":"3"},
{"name":"Rahima","project":"W1D2-4","dificulty":"1","niceness":"2"},
{"name":"Rahima","project":"W1D2-5","dificulty":"1","niceness":"3"},
{"name":"Rahima","project":"W1D3-1","dificulty":"1","niceness":"1"},
{"name":"Rahima","project":"W1D3-2","dificulty":"2","niceness":"4"},
{"name":"Rahima","project":"W1D3-4","dificulty":"1","niceness":"2"},
{"name":"Rahima","project":"W1D3-5","dificulty":"2","niceness":"2"},
{"name":"Rahima","project":"W1D3 - Project - Guess-the-number","dificulty":"3","niceness":"1"},
{"name":"Rahima","project":"W1D4-1","dificulty":"4","niceness":"3"},
{"name":"Rahima","project":"W1D4 - Project - Kleurentoggle","dificulty":"2","niceness":"4"},
{"name":"Rahima","project":"W1D5 - Project - Galgje","dificulty":"3","niceness":"3"}
,
{"name":"Rahima","project":"W2D1-1","dificulty":"2","niceness":"2"},
{"name":"Rahima","project":"W2D1-2","dificulty":"3","niceness":"1"},
{"name":"Rahima","project":"W2D2-1","dificulty":"1","niceness":"1"},
{"name":"Rahima","project":"W2D2-2","dificulty":"1","niceness":"1"},
{"name":"Rahima","project":"W2D2-3","dificulty":"4","niceness":"2"},
{"name":"Rahima","project":"W2D3-1","dificulty":"1","niceness":"1"},
{"name":"Rahima","project":"W2D3-2","dificulty":"1","niceness":"4"},
{"name":"Rahima","project":"W2D3-3","dificulty":"4","niceness":"2"},
{"name":"Rahima","project":"W2D4-1","dificulty":"4","niceness":"4"},
{"name":"Rahima","project":"W2D4-2","dificulty":"4","niceness":"4"},
{"name":"Rahima","project":"W2D4-3","dificulty":"2","niceness":"3"},
{"name":"Rahima","project":"W2D5 - Project - Filmzoeker","dificulty":"3","niceness":"1"},
{"name":"Rahima","project":"W3D1-1","dificulty":"1","niceness":"1"},
{"name":"Rahima","project":"W3D1-2","dificulty":"1","niceness":"2"},
{"name":"Rahima","project":"W3D1-3","dificulty":"2","niceness":"3"},
{"name":"Rahima","project":"W3D1-4","dificulty":"2","niceness":"4"},
{"name":"Rahima","project":"W3D2-1","dificulty":"3","niceness":"2"},
{"name":"Rahima","project":"W3D2-2","dificulty":"1","niceness":"4"},
{"name":"Rahima","project":"W3D2-3","dificulty":"2","niceness":"1"},
{"name":"Rahima","project":"W3D3-1","dificulty":"3","niceness":"1"},
{"name":"Rahima","project":"W3D3-2","dificulty":"4","niceness":"4"},
{"name":"Rahima","project":"W3D3-3","dificulty":"1","niceness":"4"},
{"name":"Rahima","project":"W3D3-4","dificulty":"2","niceness":"2"},
{"name":"Rahima","project":"W3D4-1","dificulty":"1","niceness":"2"},
{"name":"Rahima","project":"W3D4-2","dificulty":"3","niceness":"3"},
{"name":"Rahima","project":"W3D5 - Project - Todo-List","dificulty":"2","niceness":"4"},
{"name":"Rahima","project":"W4D2-1","dificulty":"2","niceness":"4"},
{"name":"Rahima","project":"W4D2-2","dificulty":"4","niceness":"3"},
{"name":"Rahima","project":"W4D2-3","dificulty":"3","niceness":"3"},
{"name":"Rahima","project":"W4D2-4","dificulty":"4","niceness":"1"},
{"name":"Rahima","project":"W4D3-1","dificulty":"2","niceness":"1"},
{"name":"Rahima","project":"W4D3-2","dificulty":"1","niceness":"1"},
{"name":"Rahima","project":"W4D3-3","dificulty":"2","niceness":"1"},
{"name":"Rahima","project":"W4D3-4","dificulty":"2","niceness":"2"},
{"name":"Rahima","project":"W4D3-5","dificulty":"3","niceness":"2"},
{"name":"Rahima","project":"W4D3 - Project - Next-Level CSS","dificulty":"1","niceness":"2"},
{"name":"Rahima","project":"W5D4-1","dificulty":"3","niceness":"3"},
{"name":"Rahima","project":"W5D5 - Project - Lil_Playlist","dificulty":"2","niceness":"3"},
{"name":"Rahima","project":"W6D1-1","dificulty":"4","niceness":"4"},
{"name":"Rahima","project":"W6D2-1","dificulty":"1","niceness":"4"},
{"name":"Rahima","project":"W6D2 - Project - Eindopdracht","dificulty":"4","niceness":"1"},
{"name":"Sandra","project":"SCRUM","dificulty":"4","niceness":"1"},
{"name":"Sandra","project":"W1D1-1","dificulty":"2","niceness":"4"},
{"name":"Sandra","project":"W1D2-1","dificulty":"3","niceness":"4"},
{"name":"Sandra","project":"W1D2-2","dificulty":"3","niceness":"2"},
{"name":"Sandra","project":"W1D2-3","dificulty":"3","niceness":"4"},
{"name":"Sandra","project":"W1D2-4","dificulty":"3","niceness":"1"},
{"name":"Sandra","project":"W1D2-5","dificulty":"4","niceness":"3"},
{"name":"Sandra","project":"W1D3-1","dificulty":"1","niceness":"1"},
{"name":"Sandra","project":"W1D3-2","dificulty":"1","niceness":"1"},
{"name":"Sandra","project":"W1D3-4","dificulty":"3","niceness":"3"},
{"name":"Sandra","project":"W1D3-5","dificulty":"4","niceness":"3"},
{"name":"Sandra","project":"W1D3 - Project - Guess-the-number","dificulty":"2","niceness":"4"},
{"name":"Sandra","project":"W1D4-1","dificulty":"3","niceness":"2"},
{"name":"Sandra","project":"W1D4 - Project - Kleurentoggle","dificulty":"1","niceness":"3"},
{"name":"Sandra","project":"W1D5 - Project - Galgje","dificulty":"3","niceness":"3"}
,
{"name":"Sandra","project":"W2D1-1","dificulty":"4","niceness":"1"},
{"name":"Sandra","project":"W2D1-2","dificulty":"4","niceness":"3"},
{"name":"Sandra","project":"W2D2-1","dificulty":"3","niceness":"4"},
{"name":"Sandra","project":"W2D2-2","dificulty":"2","niceness":"3"},
{"name":"Sandra","project":"W2D2-3","dificulty":"4","niceness":"3"},
{"name":"Sandra","project":"W2D3-1","dificulty":"1","niceness":"2"},
{"name":"Sandra","project":"W2D3-2","dificulty":"3","niceness":"2"},
{"name":"Sandra","project":"W2D3-3","dificulty":"2","niceness":"2"},
{"name":"Sandra","project":"W2D4-1","dificulty":"1","niceness":"3"},
{"name":"Sandra","project":"W2D4-2","dificulty":"2","niceness":"4"},
{"name":"Sandra","project":"W2D4-3","dificulty":"2","niceness":"2"},
{"name":"Sandra","project":"W2D5 - Project - Filmzoeker","dificulty":"2","niceness":"4"},
{"name":"Sandra","project":"W3D1-1","dificulty":"3","niceness":"3"},
{"name":"Sandra","project":"W3D1-2","dificulty":"3","niceness":"4"},
{"name":"Sandra","project":"W3D1-3","dificulty":"2","niceness":"4"},
{"name":"Sandra","project":"W3D1-4","dificulty":"2","niceness":"2"},
{"name":"Sandra","project":"W3D2-1","dificulty":"2","niceness":"4"},
{"name":"Sandra","project":"W3D2-2","dificulty":"2","niceness":"3"},
{"name":"Sandra","project":"W3D2-3","dificulty":"1","niceness":"2"},
{"name":"Sandra","project":"W3D3-1","dificulty":"1","niceness":"2"},
{"name":"Sandra","project":"W3D3-2","dificulty":"2","niceness":"2"},
{"name":"Sandra","project":"W3D3-3","dificulty":"4","niceness":"4"},
{"name":"Sandra","project":"W3D3-4","dificulty":"3","niceness":"2"},
{"name":"Sandra","project":"W3D4-1","dificulty":"2","niceness":"3"},
{"name":"Sandra","project":"W3D4-2","dificulty":"1","niceness":"1"},
{"name":"Sandra","project":"W3D5 - Project - Todo-List","dificulty":"1","niceness":"2"},
{"name":"Sandra","project":"W4D2-1","dificulty":"3","niceness":"3"},
{"name":"Sandra","project":"W4D2-2","dificulty":"1","niceness":"1"},
{"name":"Sandra","project":"W4D2-3","dificulty":"3","niceness":"4"},
{"name":"Sandra","project":"W4D2-4","dificulty":"1","niceness":"4"},
{"name":"Sandra","project":"W4D3-1","dificulty":"3","niceness":"1"},
{"name":"Sandra","project":"W4D3-2","dificulty":"1","niceness":"3"},
{"name":"Sandra","project":"W4D3-3","dificulty":"2","niceness":"4"},
{"name":"Sandra","project":"W4D3-4","dificulty":"1","niceness":"4"},
{"name":"Sandra","project":"W4D3-5","dificulty":"1","niceness":"3"},
{"name":"Sandra","project":"W4D3 - Project - Next-Level CSS","dificulty":"3","niceness":"4"},
{"name":"Sandra","project":"W5D4-1","dificulty":"1","niceness":"1"},
{"name":"Sandra","project":"W5D5 - Project - Lil_Playlist","dificulty":"2","niceness":"2"},
{"name":"Sandra","project":"W6D1-1","dificulty":"1","niceness":"4"},
{"name":"Sandra","project":"W6D2-1","dificulty":"2","niceness":"3"},
{"name":"Sandra","project":"W6D2 - Project - Eindopdracht","dificulty":"4","niceness":"1"},
{"name":"Wietske","project":"SCRUM","dificulty":"1","niceness":"1"},
{"name":"Wietske","project":"W1D1-1","dificulty":"4","niceness":"3"},
{"name":"Wietske","project":"W1D2-1","dificulty":"1","niceness":"4"},
{"name":"Wietske","project":"W1D2-2","dificulty":"1","niceness":"2"},
{"name":"Wietske","project":"W1D2-3","dificulty":"2","niceness":"3"},
{"name":"Wietske","project":"W1D2-4","dificulty":"2","niceness":"1"},
{"name":"Wietske","project":"W1D2-5","dificulty":"3","niceness":"4"},
{"name":"Wietske","project":"W1D3-1","dificulty":"1","niceness":"2"},
{"name":"Wietske","project":"W1D3-2","dificulty":"1","niceness":"4"},
{"name":"Wietske","project":"W1D3-4","dificulty":"2","niceness":"1"},
{"name":"Wietske","project":"W1D3-5","dificulty":"3","niceness":"4"},
{"name":"Wietske","project":"W1D3 - Project - Guess-the-number","dificulty":"2","niceness":"4"},
{"name":"Wietske","project":"W1D4-1","dificulty":"2","niceness":"4"},
{"name":"Wietske","project":"W1D4 - Project - Kleurentoggle","dificulty":"2","niceness":"3"},
{"name":"Wietske","project":"W1D5 - Project - Galgje","dificulty":"3","niceness":"3"}
,
{"name":"Wietske","project":"W2D1-1","dificulty":"3","niceness":"1"},
{"name":"Wietske","project":"W2D1-2","dificulty":"4","niceness":"1"},
{"name":"Wietske","project":"W2D2-1","dificulty":"2","niceness":"2"},
{"name":"Wietske","project":"W2D2-2","dificulty":"2","niceness":"4"},
{"name":"Wietske","project":"W2D2-3","dificulty":"3","niceness":"4"},
{"name":"Wietske","project":"W2D3-1","dificulty":"2","niceness":"1"},
{"name":"Wietske","project":"W2D3-2","dificulty":"1","niceness":"1"},
{"name":"Wietske","project":"W2D3-3","dificulty":"2","niceness":"3"},
{"name":"Wietske","project":"W2D4-1","dificulty":"1","niceness":"1"},
{"name":"Wietske","project":"W2D4-2","dificulty":"2","niceness":"4"},
{"name":"Wietske","project":"W2D4-3","dificulty":"4","niceness":"3"},
{"name":"Wietske","project":"W2D5 - Project - Filmzoeker","dificulty":"2","niceness":"2"},
{"name":"Wietske","project":"W3D1-1","dificulty":"1","niceness":"3"},
{"name":"Wietske","project":"W3D1-2","dificulty":"4","niceness":"4"},
{"name":"Wietske","project":"W3D1-3","dificulty":"4","niceness":"2"},
{"name":"Wietske","project":"W3D1-4","dificulty":"1","niceness":"4"},
{"name":"Wietske","project":"W3D2-1","dificulty":"3","niceness":"2"},
{"name":"Wietske","project":"W3D2-2","dificulty":"1","niceness":"3"},
{"name":"Wietske","project":"W3D2-3","dificulty":"2","niceness":"4"},
{"name":"Wietske","project":"W3D3-1","dificulty":"1","niceness":"4"},
{"name":"Wietske","project":"W3D3-2","dificulty":"3","niceness":"1"},
{"name":"Wietske","project":"W3D3-3","dificulty":"1","niceness":"3"},
{"name":"Wietske","project":"W3D3-4","dificulty":"3","niceness":"4"},
{"name":"Wietske","project":"W3D4-1","dificulty":"3","niceness":"4"},
{"name":"Wietske","project":"W3D4-2","dificulty":"4","niceness":"2"},
{"name":"Wietske","project":"W3D5 - Project - Todo-List","dificulty":"2","niceness":"4"},
{"name":"Wietske","project":"W4D2-1","dificulty":"3","niceness":"3"},
{"name":"Wietske","project":"W4D2-2","dificulty":"2","niceness":"4"},
{"name":"Wietske","project":"W4D2-3","dificulty":"1","niceness":"2"},
{"name":"Wietske","project":"W4D2-4","dificulty":"4","niceness":"3"},
{"name":"Wietske","project":"W4D3-1","dificulty":"2","niceness":"1"},
{"name":"Wietske","project":"W4D3-2","dificulty":"1","niceness":"2"},
{"name":"Wietske","project":"W4D3-3","dificulty":"1","niceness":"4"},
{"name":"Wietske","project":"W4D3-4","dificulty":"3","niceness":"4"},
{"name":"Wietske","project":"W4D3-5","dificulty":"4","niceness":"3"},
{"name":"Wietske","project":"W4D3 - Project - Next-Level CSS","dificulty":"4","niceness":"2"},
{"name":"Wietske","project":"W5D4-1","dificulty":"3","niceness":"1"},
{"name":"Wietske","project":"W5D5 - Project - Lil_Playlist","dificulty":"4","niceness":"2"},
{"name":"Wietske","project":"W6D1-1","dificulty":"1","niceness":"1"},
{"name":"Wietske","project":"W6D2-1","dificulty":"2","niceness":"1"},
{"name":"Wietske","project":"W6D2 - Project - Eindopdracht","dificulty":"1","niceness":"2"},
{"name":"Storm","project":"SCRUM","dificulty":"1","niceness":"1"},
{"name":"Storm","project":"W1D1-1","dificulty":"2","niceness":"2"},
{"name":"Storm","project":"W1D2-1","dificulty":"2","niceness":"3"},
{"name":"Storm","project":"W1D2-2","dificulty":"1","niceness":"3"},
{"name":"Storm","project":"W1D2-3","dificulty":"1","niceness":"2"},
{"name":"Storm","project":"W1D2-4","dificulty":"4","niceness":"3"},
{"name":"Storm","project":"W1D2-5","dificulty":"3","niceness":"3"},
{"name":"Storm","project":"W1D3-1","dificulty":"2","niceness":"3"},
{"name":"Storm","project":"W1D3-2","dificulty":"1","niceness":"1"},
{"name":"Storm","project":"W1D3-4","dificulty":"1","niceness":"1"},
{"name":"Storm","project":"W1D3-5","dificulty":"2","niceness":"2"},
{"name":"Storm","project":"W1D3 - Project - Guess-the-number","dificulty":"3","niceness":"4"},
{"name":"Storm","project":"W1D4-1","dificulty":"4","niceness":"2"},
{"name":"Storm","project":"W1D4 - Project - Kleurentoggle","dificulty":"3","niceness":"2"},
{"name":"Storm","project":"W1D5 - Project - Galgje","dificulty":"4","niceness":"4"}
,
{"name":"Storm","project":"W2D1-1","dificulty":"2","niceness":"4"},
{"name":"Storm","project":"W2D1-2","dificulty":"3","niceness":"2"},
{"name":"Storm","project":"W2D2-1","dificulty":"4","niceness":"4"},
{"name":"Storm","project":"W2D2-2","dificulty":"2","niceness":"1"},
{"name":"Storm","project":"W2D2-3","dificulty":"1","niceness":"1"},
{"name":"Storm","project":"W2D3-1","dificulty":"2","niceness":"3"},
{"name":"Storm","project":"W2D3-2","dificulty":"3","niceness":"4"},
{"name":"Storm","project":"W2D3-3","dificulty":"3","niceness":"2"},
{"name":"Storm","project":"W2D4-1","dificulty":"3","niceness":"4"},
{"name":"Storm","project":"W2D4-2","dificulty":"4","niceness":"3"},
{"name":"Storm","project":"W2D4-3","dificulty":"2","niceness":"1"},
{"name":"Storm","project":"W2D5 - Project - Filmzoeker","dificulty":"4","niceness":"1"},
{"name":"Storm","project":"W3D1-1","dificulty":"2","niceness":"1"},
{"name":"Storm","project":"W3D1-2","dificulty":"2","niceness":"2"},
{"name":"Storm","project":"W3D1-3","dificulty":"1","niceness":"2"},
{"name":"Storm","project":"W3D1-4","dificulty":"2","niceness":"3"},
{"name":"Storm","project":"W3D2-1","dificulty":"1","niceness":"4"},
{"name":"Storm","project":"W3D2-2","dificulty":"3","niceness":"3"},
{"name":"Storm","project":"W3D2-3","dificulty":"3","niceness":"4"},
{"name":"Storm","project":"W3D3-1","dificulty":"3","niceness":"4"},
{"name":"Storm","project":"W3D3-2","dificulty":"1","niceness":"2"},
{"name":"Storm","project":"W3D3-3","dificulty":"3","niceness":"1"},
{"name":"Storm","project":"W3D3-4","dificulty":"3","niceness":"1"},
{"name":"Storm","project":"W3D4-1","dificulty":"2","niceness":"4"},
{"name":"Storm","project":"W3D4-2","dificulty":"3","niceness":"4"},
{"name":"Storm","project":"W3D5 - Project - Todo-List","dificulty":"3","niceness":"2"},
{"name":"Storm","project":"W4D2-1","dificulty":"2","niceness":"1"},
{"name":"Storm","project":"W4D2-2","dificulty":"3","niceness":"3"},
{"name":"Storm","project":"W4D2-3","dificulty":"2","niceness":"2"},
{"name":"Storm","project":"W4D2-4","dificulty":"3","niceness":"4"},
{"name":"Storm","project":"W4D3-1","dificulty":"3","niceness":"4"},
{"name":"Storm","project":"W4D3-2","dificulty":"2","niceness":"3"},
{"name":"Storm","project":"W4D3-3","dificulty":"1","niceness":"1"},
{"name":"Storm","project":"W4D3-4","dificulty":"3","niceness":"1"},
{"name":"Storm","project":"W4D3-5","dificulty":"2","niceness":"3"},
{"name":"Storm","project":"W4D3 - Project - Next-Level CSS","dificulty":"4","niceness":"1"},
{"name":"Storm","project":"W5D4-1","dificulty":"2","niceness":"2"},
{"name":"Storm","project":"W5D5 - Project - Lil_Playlist","dificulty":"1","niceness":"2"},
{"name":"Storm","project":"W6D1-1","dificulty":"4","niceness":"4"},
{"name":"Storm","project":"W6D2-1","dificulty":"1","niceness":"1"},
{"name":"Storm","project":"W6D2 - Project - Eindopdracht","dificulty":"3","niceness":"3"}
];

export { studentData };